import { PrismaClient, Level, PartOfSpeech } from "@prisma/client";

const prisma = new PrismaClient();

const LEVELS: Level[] = ["A1", "A2", "B1", "B2", "C1", "C2"];

// Helper to create vocab item
const v = (
  word: string,
  phonBr: string,
  phonNAm: string,
  meaning: string,
  vietnameseMeaning: string,
  partOfSpeech: PartOfSpeech,
  exampleSentence: string,
  exampleTranslation: string,
  synonyms: string[] = [],
  antonyms: string[] = [],
  collocations: string[] = []
) => ({
  word,
  phonBr,
  phonNAm,
  meaning,
  vietnameseMeaning,
  partOfSpeech,
  exampleSentence,
  exampleTranslation,
  synonyms,
  antonyms,
  collocations,
});

// ============================================
// TOPIC GROUP 1: DAILY LIFE
// ============================================

const dailyLifeVocab = {
  "Home Living": {
    A1: [
      v(
        "house",
        "/haʊs/",
        "/haʊs/",
        "a building where people live",
        "nhà",
        "noun",
        "I live in a small house.",
        "Tôi sống trong một ngôi nhà nhỏ.",
        ["home"],
        [],
        ["big house"]
      ),
      v(
        "room",
        "/ruːm/",
        "/ruːm/",
        "a part of a building with walls",
        "phòng",
        "noun",
        "My room is clean.",
        "Phòng tôi sạch sẽ.",
        ["chamber"],
        [],
        ["living room"]
      ),
      v(
        "bed",
        "/bed/",
        "/bed/",
        "furniture for sleeping",
        "giường",
        "noun",
        "I sleep on my bed.",
        "Tôi ngủ trên giường.",
        [],
        [],
        ["go to bed"]
      ),
      v(
        "door",
        "/dɔːr/",
        "/dɔːr/",
        "entrance to a room or building",
        "cửa",
        "noun",
        "Please close the door.",
        "Xin hãy đóng cửa.",
        [],
        [],
        ["front door"]
      ),
      v(
        "window",
        "/ˈwɪndəʊ/",
        "/ˈwɪndoʊ/",
        "opening in wall for light",
        "cửa sổ",
        "noun",
        "Open the window please.",
        "Xin mở cửa sổ.",
        [],
        [],
        ["open window"]
      ),
      v(
        "table",
        "/ˈteɪbl/",
        "/ˈteɪbl/",
        "furniture with flat top",
        "bàn",
        "noun",
        "The book is on the table.",
        "Cuốn sách ở trên bàn.",
        ["desk"],
        [],
        ["dining table"]
      ),
      v(
        "chair",
        "/tʃeər/",
        "/tʃer/",
        "seat for one person",
        "ghế",
        "noun",
        "Sit on the chair.",
        "Ngồi lên ghế.",
        ["seat"],
        [],
        ["comfortable chair"]
      ),
      v(
        "kitchen",
        "/ˈkɪtʃɪn/",
        "/ˈkɪtʃɪn/",
        "room for cooking",
        "nhà bếp",
        "noun",
        "Mom is in the kitchen.",
        "Mẹ đang ở trong bếp.",
        [],
        [],
        ["modern kitchen"]
      ),
      v(
        "bathroom",
        "/ˈbɑːθruːm/",
        "/ˈbæθruːm/",
        "room with toilet and bath",
        "phòng tắm",
        "noun",
        "The bathroom is upstairs.",
        "Phòng tắm ở tầng trên.",
        [],
        [],
        ["clean bathroom"]
      ),
      v(
        "clean",
        "/kliːn/",
        "/kliːn/",
        "free from dirt",
        "sạch",
        "adjective",
        "My room is clean.",
        "Phòng tôi sạch.",
        ["tidy"],
        ["dirty"],
        ["keep clean"]
      ),
    ],
    A2: [
      v(
        "apartment",
        "/əˈpɑːtmənt/",
        "/əˈpɑːrtmənt/",
        "set of rooms in a building",
        "căn hộ",
        "noun",
        "I rent an apartment.",
        "Tôi thuê một căn hộ.",
        ["flat"],
        [],
        ["modern apartment"]
      ),
      v(
        "furniture",
        "/ˈfɜːnɪtʃər/",
        "/ˈfɜːrnɪtʃər/",
        "movable items in a room",
        "đồ nội thất",
        "noun",
        "We bought new furniture.",
        "Chúng tôi mua đồ nội thất mới.",
        [],
        [],
        ["wooden furniture"]
      ),
      v(
        "lamp",
        "/læmp/",
        "/læmp/",
        "device that gives light",
        "đèn",
        "noun",
        "Turn on the lamp.",
        "Bật đèn lên.",
        ["light"],
        [],
        ["table lamp"]
      ),
      v(
        "carpet",
        "/ˈkɑːpɪt/",
        "/ˈkɑːrpɪt/",
        "thick floor covering",
        "thảm",
        "noun",
        "The carpet is soft.",
        "Thảm rất mềm.",
        ["rug"],
        [],
        ["soft carpet"]
      ),
      v(
        "curtain",
        "/ˈkɜːtn/",
        "/ˈkɜːrtn/",
        "cloth covering window",
        "rèm cửa",
        "noun",
        "Close the curtains.",
        "Kéo rèm lại.",
        ["drape"],
        [],
        ["thick curtain"]
      ),
      v(
        "pillow",
        "/ˈpɪləʊ/",
        "/ˈpɪloʊ/",
        "cushion for head",
        "gối",
        "noun",
        "This pillow is soft.",
        "Gối này mềm.",
        ["cushion"],
        [],
        ["soft pillow"]
      ),
      v(
        "blanket",
        "/ˈblæŋkɪt/",
        "/ˈblæŋkɪt/",
        "cover for warmth",
        "chăn",
        "noun",
        "I need a warm blanket.",
        "Tôi cần một cái chăn ấm.",
        ["cover"],
        [],
        ["warm blanket"]
      ),
      v(
        "stairs",
        "/steəz/",
        "/sterz/",
        "steps between floors",
        "cầu thang",
        "noun",
        "Go up the stairs.",
        "Đi lên cầu thang.",
        ["steps"],
        [],
        ["climb stairs"]
      ),
      v(
        "balcony",
        "/ˈbælkəni/",
        "/ˈbælkəni/",
        "platform outside upper floor",
        "ban công",
        "noun",
        "I have plants on my balcony.",
        "Tôi có cây trên ban công.",
        [],
        [],
        ["small balcony"]
      ),
      v(
        "ceiling",
        "/ˈsiːlɪŋ/",
        "/ˈsiːlɪŋ/",
        "top surface of a room",
        "trần nhà",
        "noun",
        "The ceiling is white.",
        "Trần nhà màu trắng.",
        [],
        ["floor"],
        ["high ceiling"]
      ),
    ],
    B1: [
      v(
        "landlord",
        "/ˈlændlɔːd/",
        "/ˈlændlɔːrd/",
        "owner who rents property",
        "chủ nhà",
        "noun",
        "The landlord collects rent monthly.",
        "Chủ nhà thu tiền thuê hàng tháng.",
        ["owner"],
        ["tenant"],
        ["contact landlord"]
      ),
      v(
        "tenant",
        "/ˈtenənt/",
        "/ˈtenənt/",
        "person who rents property",
        "người thuê nhà",
        "noun",
        "The tenant pays rent on time.",
        "Người thuê trả tiền đúng hạn.",
        ["renter"],
        ["landlord"],
        ["new tenant"]
      ),
      v(
        "renovation",
        "/ˌrenəˈveɪʃn/",
        "/ˌrenəˈveɪʃn/",
        "restoring to good condition",
        "sự cải tạo",
        "noun",
        "The house needs renovation.",
        "Nhà cần được cải tạo.",
        ["repair"],
        [],
        ["home renovation"]
      ),
      v(
        "spacious",
        "/ˈspeɪʃəs/",
        "/ˈspeɪʃəs/",
        "having a lot of space",
        "rộng rãi",
        "adjective",
        "The living room is spacious.",
        "Phòng khách rộng rãi.",
        ["roomy"],
        ["cramped"],
        ["spacious room"]
      ),
      v(
        "cozy",
        "/ˈkəʊzi/",
        "/ˈkoʊzi/",
        "comfortable and warm",
        "ấm cúng",
        "adjective",
        "This is a cozy apartment.",
        "Đây là căn hộ ấm cúng.",
        ["comfortable"],
        [],
        ["cozy atmosphere"]
      ),
      v(
        "maintenance",
        "/ˈmeɪntənəns/",
        "/ˈmeɪntənəns/",
        "keeping in good condition",
        "bảo trì",
        "noun",
        "Regular maintenance is important.",
        "Bảo trì thường xuyên rất quan trọng.",
        ["upkeep"],
        [],
        ["home maintenance"]
      ),
      v(
        "appliance",
        "/əˈplaɪəns/",
        "/əˈplaɪəns/",
        "household electrical device",
        "thiết bị gia dụng",
        "noun",
        "We bought a new kitchen appliance.",
        "Chúng tôi mua thiết bị bếp mới.",
        ["device"],
        [],
        ["kitchen appliance"]
      ),
      v(
        "decorate",
        "/ˈdekəreɪt/",
        "/ˈdekəreɪt/",
        "make something look attractive",
        "trang trí",
        "verb",
        "We decorated the room.",
        "Chúng tôi trang trí phòng.",
        ["adorn"],
        [],
        ["decorate house"]
      ),
      v(
        "lease",
        "/liːs/",
        "/liːs/",
        "rental agreement",
        "hợp đồng thuê",
        "noun",
        "We signed a one-year lease.",
        "Chúng tôi ký hợp đồng thuê một năm.",
        ["contract"],
        [],
        ["sign lease"]
      ),
      v(
        "utilities",
        "/juːˈtɪlətiz/",
        "/juːˈtɪlətiz/",
        "electricity, gas, water services",
        "tiện ích",
        "noun",
        "Utilities are included in rent.",
        "Tiền điện nước đã bao gồm.",
        [],
        [],
        ["pay utilities"]
      ),
    ],
    B2: [
      v(
        "mortgage",
        "/ˈmɔːɡɪdʒ/",
        "/ˈmɔːrɡɪdʒ/",
        "loan to buy property",
        "thế chấp",
        "noun",
        "We got a 30-year mortgage.",
        "Chúng tôi vay thế chấp 30 năm.",
        ["loan"],
        [],
        ["pay mortgage"]
      ),
      v(
        "insulation",
        "/ˌɪnsjuˈleɪʃn/",
        "/ˌɪnsəˈleɪʃn/",
        "material preventing heat loss",
        "vật liệu cách nhiệt",
        "noun",
        "Good insulation saves energy.",
        "Cách nhiệt tốt tiết kiệm năng lượng.",
        [],
        [],
        ["thermal insulation"]
      ),
      v(
        "ventilation",
        "/ˌventɪˈleɪʃn/",
        "/ˌventɪˈleɪʃn/",
        "supply of fresh air",
        "thông gió",
        "noun",
        "The room needs better ventilation.",
        "Phòng cần thông gió tốt hơn.",
        [],
        [],
        ["proper ventilation"]
      ),
      v(
        "amenities",
        "/əˈmiːnətiz/",
        "/əˈmenətiz/",
        "useful features of a place",
        "tiện nghi",
        "noun",
        "The building has many amenities.",
        "Tòa nhà có nhiều tiện nghi.",
        ["facilities"],
        [],
        ["modern amenities"]
      ),
      v(
        "contemporary",
        "/kənˈtemprəri/",
        "/kənˈtemprəri/",
        "modern in style",
        "hiện đại",
        "adjective",
        "I love contemporary design.",
        "Tôi thích thiết kế hiện đại.",
        ["modern"],
        ["traditional"],
        ["contemporary style"]
      ),
      v(
        "minimalist",
        "/ˈmɪnɪməlɪst/",
        "/ˈmɪnɪməlɪst/",
        "simple, with few possessions",
        "tối giản",
        "adjective",
        "She has a minimalist home.",
        "Cô ấy có ngôi nhà tối giản.",
        ["simple"],
        ["cluttered"],
        ["minimalist design"]
      ),
      v(
        "refurbish",
        "/ˌriːˈfɜːbɪʃ/",
        "/ˌriːˈfɜːrbɪʃ/",
        "renovate and redecorate",
        "tân trang",
        "verb",
        "They refurbished the old house.",
        "Họ tân trang ngôi nhà cũ.",
        ["renovate"],
        [],
        ["refurbish property"]
      ),
      v(
        "sustainable",
        "/səˈsteɪnəbl/",
        "/səˈsteɪnəbl/",
        "environmentally responsible",
        "bền vững",
        "adjective",
        "We use sustainable materials.",
        "Chúng tôi dùng vật liệu bền vững.",
        ["eco-friendly"],
        [],
        ["sustainable living"]
      ),
      v(
        "detached",
        "/dɪˈtætʃt/",
        "/dɪˈtætʃt/",
        "not joined to another building",
        "biệt lập",
        "adjective",
        "They live in a detached house.",
        "Họ sống trong nhà biệt lập.",
        ["separate"],
        ["attached"],
        ["detached house"]
      ),
      v(
        "occupancy",
        "/ˈɒkjəpənsi/",
        "/ˈɑːkjəpənsi/",
        "the act of living in a place",
        "sự chiếm hữu",
        "noun",
        "Occupancy is limited to two.",
        "Giới hạn hai người ở.",
        [],
        [],
        ["full occupancy"]
      ),
    ],
    C1: [
      v(
        "dilapidated",
        "/dɪˈlæpɪdeɪtɪd/",
        "/dɪˈlæpɪdeɪtɪd/",
        "in a state of disrepair",
        "đổ nát",
        "adjective",
        "The dilapidated building was demolished.",
        "Tòa nhà đổ nát đã bị phá.",
        ["rundown"],
        ["pristine"],
        ["dilapidated structure"]
      ),
      v(
        "refurbishment",
        "/ˌriːˈfɜːbɪʃmənt/",
        "/ˌriːˈfɜːrbɪʃmənt/",
        "renovation and redecorating",
        "sự tân trang",
        "noun",
        "The hotel is under refurbishment.",
        "Khách sạn đang được tân trang.",
        ["renovation"],
        [],
        ["major refurbishment"]
      ),
      v(
        "domicile",
        "/ˈdɒmɪsaɪl/",
        "/ˈdɑːmɪsaɪl/",
        "permanent home",
        "nơi cư trú",
        "noun",
        "His legal domicile is London.",
        "Nơi cư trú pháp lý của anh là London.",
        ["residence"],
        [],
        ["permanent domicile"]
      ),
      v(
        "abode",
        "/əˈbəʊd/",
        "/əˈboʊd/",
        "a place of residence",
        "nơi ở",
        "noun",
        "Welcome to my humble abode.",
        "Chào mừng đến nhà nhỏ của tôi.",
        ["dwelling"],
        [],
        ["humble abode"]
      ),
      v(
        "retrofitting",
        "/ˈretrəʊfɪtɪŋ/",
        "/ˈretroʊfɪtɪŋ/",
        "adding new features to old buildings",
        "lắp đặt thêm",
        "noun",
        "Retrofitting improves energy efficiency.",
        "Lắp đặt thêm cải thiện hiệu quả năng lượng.",
        [],
        [],
        ["energy retrofitting"]
      ),
      v(
        "gentrification",
        "/ˌdʒentrɪfɪˈkeɪʃn/",
        "/ˌdʒentrɪfɪˈkeɪʃn/",
        "renovation of deteriorating areas",
        "sự quý tộc hóa",
        "noun",
        "Gentrification is changing the neighborhood.",
        "Sự quý tộc hóa đang thay đổi khu phố.",
        [],
        [],
        ["urban gentrification"]
      ),
      v(
        "dwelling",
        "/ˈdwelɪŋ/",
        "/ˈdwelɪŋ/",
        "a place where someone lives",
        "nơi cư ngụ",
        "noun",
        "This dwelling has three bedrooms.",
        "Nơi cư ngụ này có ba phòng ngủ.",
        ["residence"],
        [],
        ["private dwelling"]
      ),
      v(
        "habitation",
        "/ˌhæbɪˈteɪʃn/",
        "/ˌhæbɪˈteɪʃn/",
        "the act of living in a place",
        "sự cư trú",
        "noun",
        "The house is unfit for habitation.",
        "Ngôi nhà không phù hợp để ở.",
        ["occupancy"],
        [],
        ["human habitation"]
      ),
      v(
        "ramshackle",
        "/ˈræmʃækl/",
        "/ˈræmʃækl/",
        "badly made and likely to collapse",
        "xiêu vẹo",
        "adjective",
        "They lived in a ramshackle cottage.",
        "Họ sống trong ngôi nhà xiêu vẹo.",
        ["dilapidated"],
        ["sturdy"],
        ["ramshackle building"]
      ),
      v(
        "edifice",
        "/ˈedɪfɪs/",
        "/ˈedɪfɪs/",
        "a large impressive building",
        "tòa nhà lớn",
        "noun",
        "The cathedral is a magnificent edifice.",
        "Nhà thờ là một tòa nhà lớn tuyệt đẹp.",
        ["structure"],
        [],
        ["grand edifice"]
      ),
    ],
    C2: [
      v(
        "commodious",
        "/kəˈməʊdiəs/",
        "/kəˈmoʊdiəs/",
        "roomy and comfortable",
        "rộng rãi tiện nghi",
        "adjective",
        "The commodious hall accommodated all guests.",
        "Hội trường rộng rãi chứa được tất cả khách.",
        ["spacious"],
        ["cramped"],
        ["commodious quarters"]
      ),
      v(
        "outmoded",
        "/aʊtˈməʊdɪd/",
        "/aʊtˈmoʊdɪd/",
        "no longer fashionable or useful",
        "lỗi thời",
        "adjective",
        "These outmoded fixtures need replacing.",
        "Những thiết bị lỗi thời này cần thay thế.",
        ["obsolete"],
        ["modern"],
        ["outmoded design"]
      ),
      v(
        "decrepit",
        "/dɪˈkrepɪt/",
        "/dɪˈkrepɪt/",
        "worn out by age or neglect",
        "già nua",
        "adjective",
        "The decrepit mansion was haunted.",
        "Dinh thự già nua bị ma ám.",
        ["dilapidated"],
        ["pristine"],
        ["decrepit building"]
      ),
      v(
        "tenement",
        "/ˈtenəmənt/",
        "/ˈtenəmənt/",
        "a run-down apartment building",
        "nhà tập thể cũ",
        "noun",
        "They grew up in a tenement.",
        "Họ lớn lên trong nhà tập thể cũ.",
        [],
        [],
        ["old tenement"]
      ),
      v(
        "curtilage",
        "/ˈkɜːtɪlɪdʒ/",
        "/ˈkɜːrtɪlɪdʒ/",
        "enclosed land around a house",
        "đất bao quanh nhà",
        "noun",
        "The curtilage includes the garden.",
        "Đất bao quanh nhà bao gồm vườn.",
        [],
        [],
        ["property curtilage"]
      ),
      v(
        "hearthside",
        "/ˈhɑːθsaɪd/",
        "/ˈhɑːrθsaɪd/",
        "area around a fireplace",
        "bên lò sưởi",
        "noun",
        "We gathered at the hearthside.",
        "Chúng tôi tụ họp bên lò sưởi.",
        [],
        [],
        ["cozy hearthside"]
      ),
      v(
        "vestibule",
        "/ˈvestɪbjuːl/",
        "/ˈvestɪbjuːl/",
        "entrance hall of a building",
        "tiền sảnh",
        "noun",
        "Wait in the vestibule.",
        "Đợi ở tiền sảnh.",
        ["foyer"],
        [],
        ["building vestibule"]
      ),
      v(
        "homestead",
        "/ˈhəʊmsted/",
        "/ˈhoʊmsted/",
        "house and land around it",
        "trang trại",
        "noun",
        "The family homestead has been here for generations.",
        "Trang trại gia đình đã ở đây nhiều thế hệ.",
        ["estate"],
        [],
        ["family homestead"]
      ),
      v(
        "antechamber",
        "/ˈæntitʃeɪmbər/",
        "/ˈæntitʃeɪmbər/",
        "small room before main one",
        "phòng chờ",
        "noun",
        "Guests waited in the antechamber.",
        "Khách đợi ở phòng chờ.",
        ["anteroom"],
        [],
        ["royal antechamber"]
      ),
      v(
        "domiciliary",
        "/ˌdɒmɪˈsɪliəri/",
        "/ˌdɑːmɪˈsɪlieri/",
        "relating to someone's home",
        "thuộc về nhà ở",
        "adjective",
        "Domiciliary care is provided.",
        "Dịch vụ chăm sóc tại nhà được cung cấp.",
        [],
        [],
        ["domiciliary services"]
      ),
    ],
  },
  "Food & Drinks": {
    A1: [
      v(
        "food",
        "/fuːd/",
        "/fuːd/",
        "something people eat",
        "đồ ăn",
        "noun",
        "I like good food.",
        "Tôi thích đồ ăn ngon.",
        ["meal"],
        [],
        ["fast food"]
      ),
      v(
        "drink",
        "/drɪŋk/",
        "/drɪŋk/",
        "liquid swallowed",
        "đồ uống",
        "noun",
        "I want a cold drink.",
        "Tôi muốn một đồ uống lạnh.",
        ["beverage"],
        [],
        ["soft drink"]
      ),
      v(
        "water",
        "/ˈwɔːtər/",
        "/ˈwɔːtər/",
        "clear liquid essential for life",
        "nước",
        "noun",
        "Drink more water.",
        "Uống nhiều nước hơn.",
        [],
        [],
        ["drink water"]
      ),
      v(
        "eat",
        "/iːt/",
        "/iːt/",
        "put food in mouth",
        "ăn",
        "verb",
        "We eat dinner at 7.",
        "Chúng tôi ăn tối lúc 7 giờ.",
        ["consume"],
        [],
        ["eat healthy"]
      ),
      v(
        "fruit",
        "/fruːt/",
        "/fruːt/",
        "edible part of plant",
        "trái cây",
        "noun",
        "Eat fresh fruit.",
        "Ăn trái cây tươi.",
        [],
        [],
        ["fresh fruit"]
      ),
      v(
        "bread",
        "/bred/",
        "/bred/",
        "food made from flour",
        "bánh mì",
        "noun",
        "I eat bread for breakfast.",
        "Tôi ăn bánh mì cho bữa sáng.",
        [],
        [],
        ["fresh bread"]
      ),
      v(
        "meat",
        "/miːt/",
        "/miːt/",
        "flesh of animals as food",
        "thịt",
        "noun",
        "He doesn't eat meat.",
        "Anh ấy không ăn thịt.",
        [],
        ["vegetable"],
        ["red meat"]
      ),
      v(
        "milk",
        "/mɪlk/",
        "/mɪlk/",
        "white liquid from cows",
        "sữa",
        "noun",
        "Drink your milk.",
        "Uống sữa của bạn đi.",
        [],
        [],
        ["fresh milk"]
      ),
      v(
        "coffee",
        "/ˈkɒfi/",
        "/ˈkɔːfi/",
        "dark hot drink",
        "cà phê",
        "noun",
        "I need morning coffee.",
        "Tôi cần cà phê sáng.",
        [],
        [],
        ["black coffee"]
      ),
      v(
        "cook",
        "/kʊk/",
        "/kʊk/",
        "prepare food by heating",
        "nấu ăn",
        "verb",
        "My dad cooks well.",
        "Bố tôi nấu ăn giỏi.",
        ["prepare"],
        [],
        ["cook dinner"]
      ),
    ],
    B1: [
      v(
        "ingredient",
        "/ɪnˈɡriːdiənt/",
        "/ɪnˈɡriːdiənt/",
        "part of a mixture",
        "nguyên liệu",
        "noun",
        "Mix all ingredients.",
        "Trộn tất cả nguyên liệu.",
        ["component"],
        [],
        ["key ingredient"]
      ),
      v(
        "recipe",
        "/ˈresəpi/",
        "/ˈresəpi/",
        "instructions for cooking",
        "công thức",
        "noun",
        "Follow the recipe.",
        "Làm theo công thức.",
        [],
        [],
        ["family recipe"]
      ),
      v(
        "diet",
        "/ˈdaɪət/",
        "/ˈdaɪət/",
        "food regularly eaten",
        "chế độ ăn",
        "noun",
        "She has a healthy diet.",
        "Cô ấy có chế độ ăn lành mạnh.",
        [],
        [],
        ["balanced diet"]
      ),
      v(
        "flavour",
        "/ˈfleɪvər/",
        "/ˈfleɪvər/",
        "taste of food",
        "hương vị",
        "noun",
        "This has a spicy flavour.",
        "Cái này có vị cay.",
        ["taste"],
        [],
        ["rich flavour"]
      ),
      v(
        "portion",
        "/ˈpɔːʃn/",
        "/ˈpɔːrʃn/",
        "amount of food for one",
        "khẩu phần",
        "noun",
        "The portions are large.",
        "Khẩu phần ăn rất lớn.",
        ["serving"],
        [],
        ["portion size"]
      ),
      v(
        "bitter",
        "/ˈbɪtər/",
        "/ˈbɪtər/",
        "sharp unpleasant taste",
        "đắng",
        "adjective",
        "The coffee is too bitter.",
        "Cà phê đắng quá.",
        [],
        ["sweet"],
        ["bitter taste"]
      ),
      v(
        "vegetarian",
        "/ˌvedʒəˈteəriən/",
        "/ˌvedʒəˈteriən/",
        "eating no meat",
        "chay",
        "adjective",
        "This is a vegetarian meal.",
        "Đây là bữa ăn chay.",
        [],
        ["meat-eater"],
        ["vegetarian diet"]
      ),
      v(
        "raw",
        "/rɔː/",
        "/rɔː/",
        "not cooked",
        "sống",
        "adjective",
        "Sushi uses raw fish.",
        "Sushi dùng cá sống.",
        ["uncooked"],
        ["cooked"],
        ["raw material"]
      ),
      v(
        "roast",
        "/rəʊst/",
        "/roʊst/",
        "cook in oven",
        "quay/nướng",
        "verb",
        "We roast chicken on Sundays.",
        "Chúng tôi quay gà vào Chủ nhật.",
        ["bake"],
        [],
        ["roast beef"]
      ),
      v(
        "appetite",
        "/ˈæpɪtaɪt/",
        "/ˈæpɪtaɪt/",
        "desire to eat",
        "sự thèm ăn",
        "noun",
        "I have a big appetite.",
        "Tôi rất thèm ăn.",
        ["hunger"],
        [],
        ["loss of appetite"]
      ),
    ],
    C1: [
      v(
        "cuisine",
        "/kwɪˈziːn/",
        "/kwɪˈziːn/",
        "style of cooking",
        "ẩm thực",
        "noun",
        "I love Italian cuisine.",
        "Tôi thích ẩm thực Ý.",
        ["cooking"],
        [],
        ["local cuisine"]
      ),
      v(
        "culinary",
        "/ˈkʌlɪnəri/",
        "/ˈkʌlɪneri/",
        "related to cooking",
        "thuộc về nấu nướng",
        "adjective",
        "She has culinary skills.",
        "Cô ấy có kỹ năng nấu nướng.",
        ["gastronomic"],
        [],
        ["culinary arts"]
      ),
      v(
        "gourmet",
        "/ˈɡʊəmeɪ/",
        "/ˈɡʊrmeɪ/",
        "high quality food",
        "sành ăn",
        "adjective",
        "They sell gourmet chocolates.",
        "Họ bán sô cô la cao cấp.",
        [],
        [],
        ["gourmet food"]
      ),
      v(
        "palatable",
        "/ˈpælətəbl/",
        "/ˈpælətəbl/",
        "pleasant to taste",
        "ngon miệng",
        "adjective",
        "The meal was barely palatable.",
        "Bữa ăn hầu như không nuốt trôi.",
        ["tasty"],
        ["inedible"],
        ["palatable food"]
      ),
      v(
        "sustenance",
        "/ˈsʌstənəns/",
        "/ˈsʌstənəns/",
        "food and drink",
        "chất bổ dưỡng",
        "noun",
        "They need sustenance to survive.",
        "Họ cần thức ăn để sống sót.",
        ["nourishment"],
        [],
        ["daily sustenance"]
      ),
      v(
        "voracious",
        "/vəˈreɪʃəs/",
        "/vəˈreɪʃəs/",
        "wanting a lot of food",
        "phá mồi/tham ăn",
        "adjective",
        "He has a voracious appetite.",
        "Anh ấy ăn rất khỏe.",
        ["insatiable"],
        [],
        ["voracious eater"]
      ),
      v(
        "edible",
        "/ˈedɪbl/",
        "/ˈedɪbl/",
        "safe to eat",
        "ăn được",
        "adjective",
        "Are these mushrooms edible?",
        "Nấm này ăn được không?",
        ["eatable"],
        ["poisonous"],
        ["edible flowers"]
      ),
      v(
        "digestible",
        "/daɪˈdʒestəbl/",
        "/daɪˈdʒestəbl/",
        "easy to digest",
        "dễ tiêu",
        "adjective",
        "Rice is easily digestible.",
        "Gạo dễ tiêu hóa.",
        [],
        [],
        ["digestible food"]
      ),
      v(
        "pastry",
        "/ˈpeɪstri/",
        "/ˈpeɪstri/",
        "dough mix",
        "bánh ngọt",
        "noun",
        "French pastry is famous.",
        "Bánh ngọt Pháp rất nổi tiếng.",
        [],
        [],
        ["pastry chef"]
      ),
      v(
        "gluttony",
        "/ˈɡlʌtəni/",
        "/ˈɡlʌtəni/",
        "habit of eating too much",
        "thói phàm ăn",
        "noun",
        "Gluttony is bad for health.",
        "Phàm ăn hại sức khỏe.",
        ["greed"],
        [],
        ["sin of gluttony"]
      ),
    ],
  },
  Shopping: {
    A2: [
      v(
        "customer",
        "/ˈkʌstəmər/",
        "/ˈkʌstəmər/",
        "person buying things",
        "khách hàng",
        "noun",
        "The customer is always right.",
        "Khách hàng luôn đúng.",
        ["shopper"],
        ["seller"],
        ["loyal customer"]
      ),
      v(
        "supermarket",
        "/ˈsuːpəmɑːkɪt/",
        "/ˈsuːpərmɑːrkɪt/",
        "large food store",
        "siêu thị",
        "noun",
        "I go to the supermarket weekly.",
        "Tôi đi siêu thị hàng tuần.",
        ["grocery store"],
        [],
        ["local supermarket"]
      ),
      v(
        "price",
        "/praɪs/",
        "/praɪs/",
        "amount of money needed",
        "giá cả",
        "noun",
        "What is the price?",
        "Giá bao nhiêu?",
        ["cost"],
        [],
        ["high price"]
      ),
      v(
        "cheap",
        "/tʃiːp/",
        "/tʃiːp/",
        "low in price",
        "rẻ",
        "adjective",
        "It is very cheap.",
        "Nó rất rẻ.",
        ["inexpensive"],
        ["expensive"],
        ["cheap clothes"]
      ),
      v(
        "expensive",
        "/ɪkˈspensɪv/",
        "/ɪkˈspensɪv/",
        "costing a lot",
        "đắt",
        "adjective",
        "That car is expensive.",
        "Xe đó đắt tiền.",
        ["costly"],
        ["cheap"],
        ["expensive watch"]
      ),
      v(
        "pay",
        "/peɪ/",
        "/peɪ/",
        "give money for goods",
        "trả tiền",
        "verb",
        "I will pay by card.",
        "Tôi sẽ trả bằng thẻ.",
        ["spend"],
        [],
        ["pay bill"]
      ),
      v(
        "cash",
        "/kæʃ/",
        "/kæʃ/",
        "money in coins/notes",
        "tiền mặt",
        "noun",
        "Do you have cash?",
        "Bạn có tiền mặt không?",
        ["money"],
        [],
        ["pay cash"]
      ),
      v(
        "wallet",
        "/ˈwɒlɪt/",
        "/ˈwɑːlɪt/",
        "small case for money",
        "ví nam",
        "noun",
        "I lost my wallet.",
        "Tôi mất ví.",
        ["billfold"],
        [],
        ["leather wallet"]
      ),
      v(
        "sale",
        "/seɪl/",
        "/seɪl/",
        "selling at lower price",
        "giảm giá",
        "noun",
        "It is on sale.",
        "Nó đang giảm giá.",
        ["discount"],
        [],
        ["for sale"]
      ),
      v(
        "basket",
        "/ˈbɑːskɪt/",
        "/ˈbæskɪt/",
        "container for carrying",
        "giỏ",
        "noun",
        "Put it in the basket.",
        "Bỏ nó vào giỏ.",
        [],
        [],
        ["shopping basket"]
      ),
    ],
    B2: [
      v(
        "bargain",
        "/ˈbɑːɡən/",
        "/ˈbɑːrɡən/",
        "something sold cheaply",
        "món hời",
        "noun",
        "This shirt is a bargain.",
        "Áo này là món hời.",
        ["deal"],
        [],
        ["good bargain"]
      ),
      v(
        "consumer",
        "/kənˈsuːmər/",
        "/kənˈsuːmər/",
        "person who buys/uses",
        "người tiêu dùng",
        "noun",
        "Consumer rights are important.",
        "Quyền lợi người tiêu dùng quan trọng.",
        ["user"],
        ["producer"],
        ["consumer protection"]
      ),
      v(
        "retail",
        "/ˈriːteɪl/",
        "/ˈriːteɪl/",
        "selling to public",
        "bán lẻ",
        "noun",
        "I work in retail.",
        "Tôi làm ngành bán lẻ.",
        [],
        ["wholesale"],
        ["retail store"]
      ),
      v(
        "discount",
        "/ˈdɪskaʊnt/",
        "/ˈdɪskaʊnt/",
        "reduction in price",
        "chiết khấu",
        "noun",
        "Can I get a discount?",
        "Tôi được giảm giá không?",
        ["reduction"],
        [],
        ["big discount"]
      ),
      v(
        "purchase",
        "/ˈpɜːtʃəs/",
        "/ˈpɜːrtʃəs/",
        "act of buying",
        "mua sắm",
        "verb",
        "I purchased a new laptop.",
        "Tôi đã mua laptop mới.",
        ["buy"],
        ["sell"],
        ["make purchase"]
      ),
      v(
        "brand",
        "/brænd/",
        "/brænd/",
        "make of product",
        "thương hiệu",
        "noun",
        "Which brand do you like?",
        "Bạn thích hiệu nào?",
        ["label"],
        [],
        ["luxury brand"]
      ),
      v(
        "refund",
        "/ˈriːfʌnd/",
        "/ˈriːfʌnd/",
        "money back",
        "tiền hoàn lại",
        "noun",
        "I want a refund.",
        "Tôi muốn hoàn tiền.",
        ["repayment"],
        [],
        ["full refund"]
      ),
      v(
        "guarantee",
        "/ˌɡærənˈtiː/",
        "/ˌɡærənˈtiː/",
        "promise of quality",
        "bảo hành",
        "noun",
        "It has a 2-year guarantee.",
        "Nó có bảo hành 2 năm.",
        ["warranty"],
        [],
        ["under guarantee"]
      ),
      v(
        "boutique",
        "/buːˈtiːk/",
        "/buːˈtiːk/",
        "small fashion shop",
        "cửa hàng thời trang",
        "noun",
        "She shops at a boutique.",
        "Cô ấy mua ở cửa hàng thời trang.",
        ["shop"],
        [],
        ["fashion boutique"]
      ),
      v(
        "browse",
        "/braʊz/",
        "/braʊz/",
        "look at goods",
        "xem hàng",
        "verb",
        "I'm just browsing.",
        "Tôi chỉ đang xem thôi.",
        ["look"],
        [],
        ["browse shop"]
      ),
    ],
    C2: [
      v(
        "exorbitant",
        "/ɪɡˈzɔːbɪtənt/",
        "/ɪɡˈzɔːrbɪtənt/",
        "much too expensive",
        "cắt cổ (giá)",
        "adjective",
        "The prices are exorbitant.",
        "Giá cả quá cắt cổ.",
        ["excessive"],
        ["reasonable"],
        ["exorbitant fee"]
      ),
      v(
        "acquisition",
        "/ˌækwɪˈzɪʃn/",
        "/ˌækwɪˈzɪʃn/",
        "act of getting something",
        "sự mua lại",
        "noun",
        "His latest acquisition is a painting.",
        "Thứ anh ấy mới tậu là bức tranh.",
        ["purchase"],
        [],
        ["recent acquisition"]
      ),
      v(
        "commodity",
        "/kəˈmɒdəti/",
        "/kəˈmɑːdəti/",
        "product that is bought/sold",
        "hàng hóa",
        "noun",
        "Oil is a valuable commodity.",
        "Dầu là hàng hóa giá trị.",
        ["goods"],
        [],
        ["basic commodity"]
      ),
      v(
        "merchandise",
        "/ˈmɜːtʃəndaɪs/",
        "/ˈmɜːrtʃəndaɪs/",
        "goods for sale",
        "hàng hóa (bán)",
        "noun",
        "They display the merchandise well.",
        "Họ trưng bày hàng hóa tốt.",
        ["goods"],
        [],
        ["branded merchandise"]
      ),
      v(
        "vendor",
        "/ˈvendər/",
        "/ˈvendər/",
        "person who sells",
        "nhà cung cấp/người bán",
        "noun",
        "Street vendors sell food.",
        "Người bán hàng rong bán đồ ăn.",
        ["seller"],
        ["buyer"],
        ["street vendor"]
      ),
      v(
        "proprietor",
        "/prəˈpaɪətər/",
        "/prəˈpaɪətər/",
        "owner of a business",
        "chủ sở hữu",
        "noun",
        "The proprietor is very kind.",
        "Ông chủ rất tốt bụng.",
        ["owner"],
        [],
        ["store proprietor"]
      ),
      v(
        "clientele",
        "/ˌkliːənˈtel/",
        "/ˌklaɪənˈtel/",
        "all the customers",
        "nhóm khách hàng",
        "noun",
        "The shop has a wealthy clientele.",
        "Cửa hàng có nhóm khách giàu có.",
        ["customers"],
        [],
        ["loyal clientele"]
      ),
      v(
        "lucrative",
        "/ˈluːkrətɪv/",
        "/ˈluːkrətɪv/",
        "making a lot of money",
        "sinh lợi",
        "adjective",
        "It is a lucrative business.",
        "Nó là việc kinh doanh sinh lợi.",
        ["profitable"],
        ["unprofitable"],
        ["lucrative deal"]
      ),
      v(
        "barter",
        "/ˈbɑːtər/",
        "/ˈbɑːrtər/",
        "exchange goods for goods",
        "trao đổi hàng",
        "verb",
        "They used to barter food.",
        "Họ từng trao đổi thức ăn.",
        ["trade"],
        [],
        ["barter system"]
      ),
      v(
        "emporium",
        "/emˈpɔːriəm/",
        "/emˈpɔːriəm/",
        "large shop",
        "trung tâm mua sắm",
        "noun",
        "London has famous emporiums.",
        "London có các trung tâm mua sắm nổi tiếng.",
        ["store"],
        [],
        ["fashion emporium"]
      ),
    ],
  },
  Transportation: {
    A1: [
      v(
        "car",
        "/kɑːr/",
        "/kɑːr/",
        "road vehicle with 4 wheels",
        "ô tô",
        "noun",
        "I drive a car.",
        "Tôi lái xe ô tô.",
        ["automobile"],
        [],
        ["fast car"]
      ),
      v(
        "bus",
        "/bʌs/",
        "/bʌs/",
        "large vehicle for many",
        "xe buýt",
        "noun",
        "Take the bus home.",
        "Bắt xe buýt về nhà.",
        ["coach"],
        [],
        ["school bus"]
      ),
      v(
        "train",
        "/treɪn/",
        "/treɪn/",
        "railway vehicle",
        "tàu hỏa",
        "noun",
        "The train is late.",
        "Tàu đến muộn.",
        [],
        [],
        ["catch train"]
      ),
      v(
        "bike",
        "/baɪk/",
        "/baɪk/",
        "vehicle with 2 wheels",
        "xe đạp",
        "noun",
        "I ride my bike.",
        "Tôi đạp xe.",
        ["bicycle"],
        [],
        ["ride bike"]
      ),
      v(
        "plane",
        "/pleɪn/",
        "/pleɪn/",
        "flying vehicle",
        "máy bay",
        "noun",
        "The plane flies high.",
        "Máy bay bay cao.",
        ["airplane"],
        [],
        ["by plane"]
      ),
      v(
        "ticket",
        "/ˈtɪkɪt/",
        "/ˈtɪkɪt/",
        "paper allowing travel",
        "vé",
        "noun",
        "I need a bus ticket.",
        "Tôi cần vé xe buýt.",
        [],
        [],
        ["buy ticket"]
      ),
      v(
        "drive",
        "/draɪv/",
        "/draɪv/",
        "operate a car",
        "lái xe",
        "verb",
        "He drives to work.",
        "Anh ấy lái xe đi làm.",
        [],
        ["walk"],
        ["drive safely"]
      ),
      v(
        "road",
        "/rəʊd/",
        "/roʊd/",
        "way for cars",
        "con đường",
        "noun",
        "The road is long.",
        "Con đường rất dài.",
        ["street"],
        [],
        ["main road"]
      ),
      v(
        "stop",
        "/stɒp/",
        "/stɑːp/",
        "place to get on bus",
        "trạm dừng",
        "noun",
        "Wait at the bus stop.",
        "Đợi ở trạm xe buýt.",
        ["station"],
        [],
        ["bus stop"]
      ),
      v(
        "go",
        "/ɡəʊ/",
        "/ɡoʊ/",
        "move travel",
        "đi",
        "verb",
        "We go by car.",
        "Chúng tôi đi bằng ô tô.",
        ["travel"],
        ["stay"],
        ["go home"]
      ),
    ],
    B2: [
      v(
        "commute",
        "/kəˈmjuːt/",
        "/kəˈmjuːt/",
        "travel to work",
        "đi làm",
        "verb",
        "I commute by train.",
        "Tôi đi làm bằng tàu.",
        ["travel"],
        [],
        ["daily commute"]
      ),
      v(
        "congestion",
        "/kənˈdʒestʃən/",
        "/kənˈdʒestʃən/",
        "too much traffic",
        "tắc nghẽn",
        "noun",
        "Traffic congestion is bad.",
        "Tắc đường rất tệ.",
        ["jam"],
        [],
        ["traffic congestion"]
      ),
      v(
        "vehicle",
        "/ˈviːəkl/",
        "/ˈviːəkl/",
        "machine for travel",
        "phương tiện",
        "noun",
        "Do not leave vehicle unattended.",
        "Không để phương tiện không trông coi.",
        ["transport"],
        [],
        ["motor vehicle"]
      ),
      v(
        "passenger",
        "/ˈpæsɪndʒər/",
        "/ˈpæsɪndʒər/",
        "person travelling",
        "hành khách",
        "noun",
        "The bus was full of passengers.",
        "Xe buýt đầy hành khách.",
        ["traveller"],
        ["driver"],
        ["train passenger"]
      ),
      v(
        "depart",
        "/dɪˈpɑːt/",
        "/dɪˈpɑːrt/",
        "leave a place",
        "khởi hành",
        "verb",
        "Values depart at 9.",
        "Chuyến tàu đi lúc 9 giờ.",
        ["leave"],
        ["arrive"],
        ["depart for"]
      ),
      v(
        "arrival",
        "/əˈraɪvl/",
        "/əˈraɪvl/",
        "reaching a place",
        "sự đến",
        "noun",
        "Check arrival time.",
        "Kiểm tra giờ đến.",
        ["coming"],
        ["departure"],
        ["estimated arrival"]
      ),
      v(
        "fare",
        "/feər/",
        "/fer/",
        "cost of travel",
        "giá vé",
        "noun",
        "Bus fares increased.",
        "Giá vé xe buýt tăng.",
        ["price"],
        [],
        ["pay fare"]
      ),
      v(
        "pedestrian",
        "/pəˈdestriən/",
        "/pəˈdestriən/",
        "person walking",
        "người đi bộ",
        "noun",
        "Watch out for pedestrians.",
        "Cẩn thận người đi bộ.",
        ["walker"],
        ["driver"],
        ["pedestrian crossing"]
      ),
      v(
        "route",
        "/ruːt/",
        "/ruːt/",
        "way to go",
        "lộ trình",
        "noun",
        "This is the fastest route.",
        "Đây là lộ trình nhanh nhất.",
        ["path"],
        [],
        ["planned route"]
      ),
      v(
        "transfer",
        "/trænsˈfɜːr/",
        "/trænsˈfɜːr/",
        "change to another bus/train",
        "chuyển xe",
        "verb",
        "Transfer at the next station.",
        "Chuyển xe ở trạm tới.",
        ["switch"],
        [],
        ["transfer flight"]
      ),
    ],
    C1: [
      v(
        "itinerary",
        "/aɪˈtɪnərəri/",
        "/aɪˈtɪnərəri/",
        "plan of a journey",
        "lịch trình",
        "noun",
        "Send me your itinerary.",
        "Gửi tôi lịch trình của bạn.",
        ["schedule"],
        [],
        ["travel itinerary"]
      ),
      v(
        "logistics",
        "/ləˈdʒɪstɪks/",
        "/ləˈdʒɪstɪks/",
        "organization of complex operation",
        "hậu cần",
        "noun",
        "Transport logistics are complex.",
        "Hậu cần vận tải rất phức tạp.",
        [],
        [],
        ["supply logistics"]
      ),
      v(
        "freight",
        "/freɪt/",
        "/freɪt/",
        "goods carried by transport",
        "hàng hóa chuyên chở",
        "noun",
        "The train carries heavy freight.",
        "Tàu chở hàng nặng.",
        ["cargo"],
        [],
        ["freight train"]
      ),
      v(
        "gridlock",
        "/ˈɡrɪdlɒk/",
        "/ˈɡrɪdlɑːk/",
        "severe traffic jam",
        "tắc nghẽn hoàn toàn",
        "noun",
        "The city is in gridlock.",
        "Thành phố bị tắc nghẽn hoàn toàn.",
        ["jam"],
        ["flow"],
        ["traffic gridlock"]
      ),
      v(
        "infrastructure",
        "/ˈɪnfrəstrʌktʃər/",
        "/ˈɪnfrəstrʌktʃər/",
        "basic systems",
        "cơ sở hạ tầng",
        "noun",
        "Improve transport infrastructure.",
        "Cải thiện cơ sở hạ tầng giao thông.",
        ["system"],
        [],
        ["public infrastructure"]
      ),
      v(
        "terminal",
        "/ˈtɜːmɪnl/",
        "/ˈtɜːrmɪnl/",
        "end station",
        "nhà ga cuối/bến",
        "noun",
        "Go to Terminal 2.",
        "Đến Nhà ga số 2.",
        ["station"],
        [],
        ["airport terminal"]
      ),
      v(
        "shuttle",
        "/ˈʃʌtl/",
        "/ˈʃʌtl/",
        "regular short journey vehicle",
        "xe trung chuyển",
        "noun",
        "Take the airport shuttle.",
        "Bắt xe trung chuyển sân bay.",
        [],
        [],
        ["shuttle bus"]
      ),
      v(
        "transit",
        "/ˈtrænzɪt/",
        "/ˈtrænzɪt/",
        "carrying people/goods",
        "quá cảnh/vận chuyển",
        "noun",
        "Goods are in transit.",
        "Hàng hóa đang trên đường vận chuyển.",
        ["transport"],
        [],
        ["mass transit"]
      ),
      v(
        "embark",
        "/ɪmˈbɑːk/",
        "/ɪmˈbɑːrk/",
        "go on board",
        "lên tàu/xe",
        "verb",
        "We embarked on the ship.",
        "Chúng tôi lên tàu.",
        ["board"],
        ["disembark"],
        ["embark on journey"]
      ),
      v(
        "divert",
        "/daɪˈvɜːt/",
        "/daɪˈvɜːrt/",
        "change direction",
        "chuyển hướng",
        "verb",
        "Traffic was diverted.",
        "Giao thông bị chuyển hướng.",
        ["redirect"],
        [],
        ["divert flight"]
      ),
    ],
  },
};

// Seed function
async function seedVocab() {
  console.log("🌱 Seeding Vocabulary Data - Daily Life...");

  // Get or create topic group
  const topicGroup = await prisma.topicGroup.upsert({
    where: { name_hubType: { name: "Daily Life", hubType: "vocab" } },
    update: {},
    create: {
      name: "Daily Life",
      order: 1,
      hubType: "vocab",
      subcategories: [
        "Home Living",
        "Food & Drinks",
        "Shopping",
        "Transportation",
      ],
    },
  });

  // Helper to slugify
  const slugify = (text: string) =>
    text.toLowerCase().replace(/&/g, "and").replace(/\s+/g, "-");

  // Iterate over all subcategories in dailyLifeVocab
  for (const [subcat, levelsData] of Object.entries(dailyLifeVocab)) {
    console.log(`Processing Subcategory: ${subcat}`);

    // Iterate over levels present in this subcategory
    for (const [level, vocabItems] of Object.entries(levelsData)) {
      // Loop over levels provided
      const currentLevel = level as Level;
      const items = vocabItems as ReturnType<typeof v>[]; // Cast to correct type

      if (!items || items.length === 0) continue;

      const topicId = `daily-life-${slugify(
        subcat
      )}-${currentLevel.toLowerCase()}`;

      const topic = await prisma.topic.upsert({
        where: { id: topicId },
        update: { wordCount: items.length },
        create: {
          id: topicId,
          title: `${subcat} - ${currentLevel}`,
          subtitle: `Vocabulary about ${subcat.toLowerCase()}`,
          description: `Learn essential vocabulary about ${subcat.toLowerCase()} at ${currentLevel} level.`,
          level: currentLevel,
          wordCount: items.length,
          estimatedTime: Math.ceil(items.length * 2),
          category: "Daily Life",
          subcategory: subcat,
          order: LEVELS.indexOf(currentLevel),
          topicGroupId: topicGroup.id,
        },
      });

      // Seed vocab items
      for (const vocab of items) {
        const vocabId = `${topic.id}-${vocab.word
          .toLowerCase()
          .replace(/\s+/g, "-")}`;
        await prisma.vocabItem.upsert({
          where: { id: vocabId },
          update: vocab,
          create: {
            id: vocabId,
            topicId: topic.id,
            ...vocab,
          },
        });
      }
      console.log(
        `✅ Created: ${subcat} - ${currentLevel} (${items.length} words)`
      );
    }
  }

  console.log("✅ Daily Life seeded successfully!");
}

async function main() {
  try {
    await seedVocab();
  } catch (error) {
    console.error("❌ Error:", error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

main();
