import { PrismaClient, Level, PartOfSpeech } from "@prisma/client";

const prisma = new PrismaClient();

const LEVELS: Level[] = ["A1", "A2", "B1", "B2", "C1", "C2"];

// Helper to create vocab item
const v = (
  word: string,
  phonBr: string,
  phonNAm: string,
  meaning: string,
  vietnameseMeaning: string,
  partOfSpeech: PartOfSpeech,
  exampleSentence: string,
  exampleTranslation: string,
  synonyms: string[] = [],
  antonyms: string[] = [],
  collocations: string[] = []
) => ({
  word,
  phonBr,
  phonNAm,
  meaning,
  vietnameseMeaning,
  partOfSpeech,
  exampleSentence,
  exampleTranslation,
  synonyms,
  antonyms,
  collocations,
});

// ============================================
// TOPIC GROUP 6: ENTERTAINMENT
// ============================================

const entertainmentVocab = {
  "Movies & TV": {
    A1: [
      v(
        "film",
        "/fɪlm/",
        "/fɪlm/",
        "movie",
        "phim",
        "noun",
        "Watch a film.",
        "Xem phim.",
        ["movie"],
        [],
        ["good film"]
      ),
      v(
        "cinema",
        "/ˈsɪnəmə/",
        "/ˈsɪnəmə/",
        "place for films",
        "rạp chiếu phim",
        "noun",
        "Go to the cinema.",
        "Đi xem phim.",
        ["theaters"],
        [],
        ["local cinema"]
      ),
      v(
        "actor",
        "/ˈæktər/",
        "/ˈæktər/",
        "person in film",
        "diễn viên nam",
        "noun",
        "Famous actor.",
        "Diễn viên nổi tiếng.",
        [],
        [],
        ["best actor"]
      ),
      v(
        "star",
        "/stɑːr/",
        "/stɑːr/",
        "famous person",
        "ngôi sao",
        "noun",
        "Movie star.",
        "Ngôi sao điện ảnh.",
        ["celebrity"],
        [],
        ["pop star"]
      ),
      v(
        "watch",
        "/wɒtʃ/",
        "/wɑːtʃ/",
        "look at",
        "xem",
        "verb",
        "Watch TV.",
        "Xem tivi.",
        ["view"],
        [],
        ["watch movie"]
      ),
      v(
        "show",
        "/ʃəʊ/",
        "/ʃoʊ/",
        "TV program",
        "chương trình",
        "noun",
        "Funny show.",
        "Chương trình hài hước.",
        ["program"],
        [],
        ["tv show"]
      ),
      v(
        "funny",
        "/ˈfʌni/",
        "/ˈfʌni/",
        "making laugh",
        "buồn cười",
        "adjective",
        "It is funny.",
        "Nó rất buồn cười.",
        ["amusing"],
        ["sad"],
        ["very funny"]
      ),
      v(
        "sad",
        "/sæd/",
        "/sæd/",
        "making cry",
        "buồn",
        "adjective",
        "Sad movie.",
        "Phim buồn.",
        ["unhappy"],
        ["happy"],
        ["feel sad"]
      ),
      v(
        "ticket",
        "/ˈtɪkɪt/",
        "/ˈtɪkɪt/",
        "paper to enter",
        "vé",
        "noun",
        "Buy a ticket.",
        "Mua vé.",
        [],
        [],
        ["cinema ticket"]
      ),
      v(
        "seat",
        "/siːt/",
        "/siːt/",
        "chair",
        "chỗ ngồi",
        "noun",
        "Take a seat.",
        "Ngồi xuống.",
        ["chair"],
        [],
        ["front seat"]
      ),
    ],
    B1: [
      v(
        "genre",
        "/ˈʒɒnrə/",
        "/ˈʒɑːnrə/",
        "style of art",
        "thể loại",
        "noun",
        "Horror genre.",
        "Thể loại kinh dị.",
        ["style"],
        [],
        ["movie genre"]
      ),
      v(
        "comedy",
        "/ˈkɒmədi/",
        "/ˈkɑːmədi/",
        "funny film",
        "phim hài",
        "noun",
        "Romantic comedy.",
        "Phim hài lãng mạn.",
        [],
        ["tragedy"],
        ["watch comedy"]
      ),
      v(
        "drama",
        "/ˈdrɑːmə/",
        "/ˈdrɑːmə/",
        "serious film",
        "phim chính kịch",
        "noun",
        "Family drama.",
        "Phim gia đình.",
        [],
        [],
        ["period drama"]
      ),
      v(
        "scene",
        "/siːn/",
        "/siːn/",
        "part of film",
        "cảnh phim",
        "noun",
        "Action scene.",
        "Cảnh hành động.",
        [],
        [],
        ["opening scene"]
      ),
      v(
        "plot",
        "/plɒt/",
        "/plɑːt/",
        "story of film",
        "cốt truyện",
        "noun",
        "Complex plot.",
        "Cốt truyện phức tạp.",
        ["storyline"],
        [],
        ["follow plot"]
      ),
      v(
        "character",
        "/ˈkærəktər/",
        "/ˈkærəktər/",
        "person in story",
        "nhân vật",
        "noun",
        "Main character.",
        "Nhân vật chính.",
        [],
        [],
        ["favorite character"]
      ),
      v(
        "audience",
        "/ˈɔːdiəns/",
        "/ˈɔːdiəns/",
        "people watching",
        "khán giả",
        "noun",
        "Large audience.",
        "Đông đảo khán giả.",
        ["viewers"],
        [],
        ["target audience"]
      ),
      v(
        "screenplay",
        "/ˈskriːnpleɪ/",
        "/ˈskriːnpleɪ/",
        "written story",
        "kịch bản",
        "noun",
        "Write a screenplay.",
        "Viết kịch bản.",
        ["script"],
        [],
        ["original screenplay"]
      ),
      v(
        "director",
        "/dəˈrektər/",
        "/dəˈrektər/",
        "person making film",
        "đạo diễn",
        "noun",
        "Film director.",
        "Đạo diễn phim.",
        [],
        [],
        ["famous director"]
      ),
      v(
        "series",
        "/ˈsɪəriːz/",
        "/ˈsɪriːz/",
        "set of episodes",
        "phim bộ",
        "noun",
        "TV series.",
        "Phim truyền hình nhiều tập.",
        [],
        [],
        ["watch series"]
      ),
    ],
    C2: [
      v(
        "cinematography",
        "/ˌsɪnəməˈtɒɡrəfi/",
        "/ˌsɪnəməˈtɑːɡrəfi/",
        "art of camera work",
        "nghệ thuật quay phim",
        "noun",
        "Stunning cinematography.",
        "Kỹ thuật quay phim tuyệt đẹp.",
        [],
        [],
        ["director of cinematography"]
      ),
      v(
        "protagonist",
        "/prəˈtæɡənɪst/",
        "/prəˈtæɡənɪst/",
        "main character",
        "nhân vật chính diện",
        "noun",
        "Heroic protagonist.",
        "Nhân vật chính anh hùng.",
        ["hero"],
        ["antagonist"],
        ["main protagonist"]
      ),
      v(
        "antagonist",
        "/ænˈtæɡənɪst/",
        "/ænˈtæɡənɪst/",
        "villain",
        "nhân vật phản diện",
        "noun",
        "Evil antagonist.",
        "Kẻ phản diện độc ác.",
        ["villain"],
        ["protagonist"],
        ["main antagonist"]
      ),
      v(
        "blockbuster",
        "/ˈblɒkbʌstər/",
        "/ˈblɑːkbʌstər/",
        "very popular film",
        "phim bom tấn",
        "noun",
        "Summer blockbuster.",
        "Bom tấn mùa hè.",
        ["hit"],
        ["flop"],
        ["hollywood blockbuster"]
      ),
      v(
        "premiere",
        "/ˈpremieər/",
        "/prɪˈmɪr/",
        "first showing",
        "buổi công chiếu",
        "noun",
        "World premiere.",
        "Công chiếu toàn cầu.",
        ["debut"],
        [],
        ["attend premiere"]
      ),
      v(
        "cameo",
        "/ˈkæmiəʊ/",
        "/ˈkæmioʊ/",
        "short appearance",
        "vai khách mời",
        "noun",
        "Celebrity cameo.",
        "Sự xuất hiện của người nổi tiếng.",
        [],
        [],
        ["make a cameo"]
      ),
      v(
        "sequel",
        "/ˈsiːkwəl/",
        "/ˈsiːkwəl/",
        "next film",
        "phần tiếp theo",
        "noun",
        "Movie sequel.",
        "Phần kế tiếp của phim.",
        ["follow-up"],
        ["prequel"],
        ["long-awaited sequel"]
      ),
      v(
        "prequel",
        "/ˈpriːkwəl/",
        "/ˈpriːkwəl/",
        "film set before",
        "phần tiền truyện",
        "noun",
        "Star Wars prequel.",
        "Tiền truyện Star Wars.",
        [],
        ["sequel"],
        ["planned prequel"]
      ),
      v(
        "climax",
        "/ˈklaɪmæks/",
        "/ˈklaɪmæks/",
        "exciting end part",
        "cao trào",
        "noun",
        "Dramatic climax.",
        "Cao trào kịch tính.",
        ["peak"],
        [],
        ["reach climax"]
      ),
      v(
        "spoiler",
        "/ˈspɔɪlər/",
        "/ˈspɔɪlər/",
        "revealing ending",
        "tiết lộ nội dung",
        "noun",
        "No spoilers!",
        "Đừng tiết lộ nội dung!",
        [],
        [],
        ["spoiler alert"]
      ),
    ],
  },
  Music: {
    A1: [
      v(
        "music",
        "/ˈmjuːzɪk/",
        "/ˈmjuːzɪk/",
        "sounds for listening",
        "âm nhạc",
        "noun",
        "Listen to music.",
        "Nghe nhạc.",
        [],
        [],
        ["pop music"]
      ),
      v(
        "song",
        "/sɒŋ/",
        "/sɔːŋ/",
        "short piece of music",
        "bài hát",
        "noun",
        "Sing a song.",
        "Hát một bài.",
        [],
        [],
        ["love song"]
      ),
      v(
        "sing",
        "/sɪŋ/",
        "/sɪŋ/",
        "make music with voice",
        "hát",
        "verb",
        "Can you sing?",
        "Bạn biết hát không?",
        [],
        [],
        ["sing together"]
      ),
      v(
        "band",
        "/bænd/",
        "/bænd/",
        "group of musicians",
        "ban nhạc",
        "noun",
        "Rock band.",
        "Ban nhạc Rock.",
        ["group"],
        [],
        ["live band"]
      ),
      v(
        "dance",
        "/dɑːns/",
        "/dæns/",
        "move to music",
        "nhảy",
        "verb",
        "Dance with me.",
        "Nhảy với tôi đi.",
        [],
        [],
        ["dance floor"]
      ),
      v(
        "radio",
        "/ˈreɪdiəʊ/",
        "/ˈreɪdioʊ/",
        "device for music",
        "đài",
        "noun",
        "On the radio.",
        "Trên đài.",
        [],
        [],
        ["turn on radio"]
      ),
      v(
        "loud",
        "/laʊd/",
        "/laʊd/",
        "big sound",
        "to",
        "adjective",
        "Loud music.",
        "Nhạc to.",
        ["noisy"],
        ["quiet"],
        ["too loud"]
      ),
      v(
        "listen",
        "/ˈlɪsn/",
        "/ˈlɪsn/",
        "hear with attention",
        "nghe",
        "verb",
        "Listen to this.",
        "Nghe cái này nè.",
        [],
        [],
        ["listen music"]
      ),
      v(
        "play",
        "/pleɪ/",
        "/pleɪ/",
        "make music",
        "chơi (nhạc)",
        "verb",
        "Play guitar.",
        "Chơi đàn guitar.",
        [],
        [],
        ["play piano"]
      ),
      v(
        "star",
        "/stɑːr/",
        "/stɑːr/",
        "famous singer",
        "ngôi sao",
        "noun",
        "Pop star.",
        "Ngôi sao nhạc Pop.",
        [],
        [],
        ["rock star"]
      ),
    ],
    B2: [
      v(
        "lyrics",
        "/ˈlɪrɪks/",
        "/ˈlɪrɪks/",
        "words of song",
        "lời bài hát",
        "noun",
        "Meaningful lyrics.",
        "Lời bài hát ý nghĩa.",
        ["words"],
        [],
        ["write lyrics"]
      ),
      v(
        "rhythm",
        "/ˈrɪðəm/",
        "/ˈrɪðəm/",
        "beat of music",
        "nhịp điệu",
        "noun",
        "Fast rhythm.",
        "Nhịp điệu nhanh.",
        ["beat"],
        [],
        ["got rhythm"]
      ),
      v(
        "melody",
        "/ˈmelədi/",
        "/ˈmelədi/",
        "tune",
        "giai điệu",
        "noun",
        "Beautiful melody.",
        "Giai điệu đẹp.",
        ["tune"],
        [],
        ["catchy melody"]
      ),
      v(
        "instrument",
        "/ˈɪnstrəmənt/",
        "/ˈɪnstrəmənt/",
        "device for music",
        "nhạc cụ",
        "noun",
        "Musical instrument.",
        "Nhạc cụ.",
        [],
        [],
        ["play instrument"]
      ),
      v(
        "genre",
        "/ˈʒɒnrə/",
        "/ˈʒɑːnrə/",
        "type of music",
        "thể loại",
        "noun",
        "Music genre.",
        "Thể loại nhạc.",
        ["style"],
        [],
        ["favorite genre"]
      ),
      v(
        "composer",
        "/kəmˈpəʊzər/",
        "/kəmˈpoʊzər/",
        "person writing music",
        "nhà soạn nhạc",
        "noun",
        "Classical composer.",
        "Nhà soạn nhạc cổ điển.",
        ["writer"],
        [],
        ["famous composer"]
      ),
      v(
        "orchestra",
        "/ˈɔːkɪstrə/",
        "/ˈɔːrkɪstrə/",
        "large music group",
        "dàn nhạc",
        "noun",
        "Symphony orchestra.",
        "Dàn nhạc giao hưởng.",
        [],
        [],
        ["conduct orchestra"]
      ),
      v(
        "performance",
        "/pəˈfɔːməns/",
        "/pərˈfɔːrməns/",
        "show",
        "buổi biểu diễn",
        "noun",
        "Live performance.",
        "Biểu diễn trực tiếp.",
        ["show"],
        [],
        ["give performance"]
      ),
      v(
        "album",
        "/ˈælbəm/",
        "/ˈælbəm/",
        "collection of songs",
        "album",
        "noun",
        "New album.",
        "Album mới.",
        ["record"],
        [],
        ["debut album"]
      ),
      v(
        "track",
        "/træk/",
        "/træk/",
        "one song",
        "bản thu/bài",
        "noun",
        "Bonus track.",
        "Bài hát tặng kèm.",
        ["song"],
        [],
        ["sound track"]
      ),
    ],
    C1: [
      v(
        "acoustic",
        "/əˈkuːstɪk/",
        "/əˈkuːstɪk/",
        "not electric",
        "mộc/không điện",
        "adjective",
        "Acoustic guitar.",
        "Đàn guitar thùng.",
        [],
        [],
        ["acoustic session"]
      ),
      v(
        "repertoire",
        "/ˈrepətwɑːr/",
        "/ˈrepərtwɑːr/",
        "list of songs known",
        "tiết mục",
        "noun",
        "Wide repertoire.",
        "Danh mục tiết mục rộng.",
        [],
        [],
        ["piano repertoire"]
      ),
      v(
        "symphony",
        "/ˈsɪmfəni/",
        "/ˈsɪmfəni/",
        "long piece for orchestra",
        "bản giao hưởng",
        "noun",
        "Beethoven's symphony.",
        "Giao hưởng Beethoven.",
        [],
        [],
        ["ninth symphony"]
      ),
      v(
        "conductor",
        "/kənˈdʌktər/",
        "/kənˈdʌktər/",
        "leader of orchestra",
        "nhạc trưởng",
        "noun",
        "Orchestra conductor.",
        "Nhạc trưởng dàn nhạc.",
        ["director"],
        [],
        ["chief conductor"]
      ),
      v(
        "harmony",
        "/ˈhɑːməni/",
        "/ˈhɑːrməni/",
        "pleasant sound together",
        "sự hòa âm",
        "noun",
        "Vocal harmony.",
        "Hòa âm giọng hát.",
        [],
        [],
        ["perfect harmony"]
      ),
      v(
        "improvisation",
        "/ˌɪmprəvaɪˈzeɪʃn/",
        "/ˌɪmprəvaɪˈzeɪʃn/",
        "making up as playing",
        "sự ngẫu hứng",
        "noun",
        "Jazz improvisation.",
        "Ngẫu hứng Jazz.",
        [],
        [],
        ["skillful improvisation"]
      ),
      v(
        "vocalist",
        "/ˈvəʊkəlɪst/",
        "/ˈvoʊkəlɪst/",
        "singer",
        "ca sĩ (chuyên nghiệp)",
        "noun",
        "Lead vocalist.",
        "Ca sĩ chính.",
        ["singer"],
        [],
        ["backing vocalist"]
      ),
      v(
        "audition",
        "/ɔːˈdɪʃn/",
        "/ɔːˈdɪʃn/",
        "test for role",
        "buổi thử giọng",
        "noun",
        "Go to an audition.",
        "Đi thử giọng.",
        ["trial"],
        [],
        ["pass audition"]
      ),
      v(
        "choreography",
        "/ˌkɒriˈɒɡrəfi/",
        "/ˌkɔːriˈɑːɡrəfi/",
        "dance design",
        "biên đạo múa",
        "noun",
        "Complex choreography.",
        "Vũ đạo phức tạp.",
        [],
        [],
        ["dance choreography"]
      ),
      v(
        "anthem",
        "/ˈænθəm/",
        "/ˈænθəm/",
        "important song",
        "bài ca/quốc ca",
        "noun",
        "National anthem.",
        "Quốc ca.",
        [],
        [],
        ["party anthem"]
      ),
    ],
  },
  Gaming: {
    A2: [
      v(
        "game",
        "/ɡeɪm/",
        "/ɡeɪm/",
        "fun activity",
        "trò chơi",
        "noun",
        "Video game.",
        "Trò chơi điện tử.",
        [],
        [],
        ["play game"]
      ),
      v(
        "player",
        "/ˈpleɪər/",
        "/ˈpleɪər/",
        "person playing",
        "người chơi",
        "noun",
        "Multi-player.",
        "Nhiều người chơi.",
        ["gamer"],
        [],
        ["best player"]
      ),
      v(
        "level",
        "/ˈlevl/",
        "/ˈlevl/",
        "stage of game",
        "cấp độ",
        "noun",
        "Next level.",
        "Cấp độ tiếp theo.",
        ["stage"],
        [],
        ["high level"]
      ),
      v(
        "win",
        "/wɪn/",
        "/wɪn/",
        "be first/best",
        "thắng",
        "verb",
        "Win the game.",
        "Thắng trò chơi.",
        ["succeed"],
        ["lose"],
        ["win prize"]
      ),
      v(
        "lose",
        "/luːz/",
        "/luːz/",
        "not win",
        "thua",
        "verb",
        "Don't lose.",
        "Đừng thua.",
        ["fail"],
        ["win"],
        ["lose game"]
      ),
      v(
        "score",
        "/skɔːr/",
        "/skɔːr/",
        "points",
        "điểm số",
        "noun",
        "High score.",
        "Điểm cao.",
        ["points"],
        [],
        ["get score"]
      ),
      v(
        "team",
        "/tiːm/",
        "/tiːm/",
        "group playing",
        "đội",
        "noun",
        "Join a team.",
        "Gia nhập đội.",
        ["group"],
        [],
        ["team work"]
      ),
      v(
        "fun",
        "/fʌn/",
        "/fʌn/",
        "enjoyment",
        "vui vẻ",
        "noun",
        "Have fun.",
        "Vui vẻ nhé.",
        ["enjoyment"],
        [],
        ["just for fun"]
      ),
      v(
        "screen",
        "/skriːn/",
        "/skriːn/",
        "display",
        "màn hình",
        "noun",
        "Look at screen.",
        "Nhìn màn hình.",
        [],
        [],
        ["wide screen"]
      ),
      v(
        "online",
        "/ˌɒnˈlaɪn/",
        "/ˌɑːnˈlaɪn/",
        "on internet",
        "trực tuyến",
        "adjective",
        "Play online.",
        "Chơi trực tuyến.",
        [],
        ["offline"],
        ["online game"]
      ),
    ],
    B2: [
      v(
        "console",
        "/ˈkɒnsəʊl/",
        "/ˈkɑːnsoʊl/",
        "gaming machine",
        "máy chơi game",
        "noun",
        "Game console.",
        "Máy chơi game console.",
        [],
        [],
        ["new console"]
      ),
      v(
        "graphics",
        "/ˈɡræfɪks/",
        "/ˈɡræfɪks/",
        "images",
        "đồ họa",
        "noun",
        "Stunning graphics.",
        "Đồ họa tuyệt đẹp.",
        ["visuals"],
        [],
        ["3D graphics"]
      ),
      v(
        "character",
        "/ˈkærəktər/",
        "/ˈkærəktər/",
        "person in game",
        "nhân vật",
        "noun",
        "Choose your character.",
        "Chọn nhân vật.",
        ["avatar"],
        [],
        ["game character"]
      ),
      v(
        "strategy",
        "/ˈstrætədʒi/",
        "/ˈstrætədʒi/",
        "plan to win",
        "chiến thuật",
        "noun",
        "Good strategy.",
        "Chiến thuật tốt.",
        ["plan"],
        [],
        ["game strategy"]
      ),
      v(
        "virtual",
        "/ˈvɜːtʃuəl/",
        "/ˈvɜːrtʃuəl/",
        "computer generated",
        "ảo",
        "adjective",
        "Virtual reality.",
        "Thực tế ảo.",
        [],
        ["real"],
        ["virtual world"]
      ),
      v(
        "controller",
        "/kənˈtrəʊlər/",
        "/kənˈtroʊlər/",
        "device to play",
        "tay cầm",
        "noun",
        "Wireless controller.",
        "Tay cầm không dây.",
        [],
        [],
        ["game controller"]
      ),
      v(
        "stream",
        "/striːm/",
        "/striːm/",
        "broadcast online",
        "phát trực tiếp",
        "verb",
        "Stream gameplay.",
        "Phát trực tiếp chơi game.",
        ["broadcast"],
        [],
        ["live stream"]
      ),
      v(
        "esports",
        "/ˈiːspɔːts/",
        "/ˈiːspɔːrts/",
        "competitive gaming",
        "thể thao điện tử",
        "noun",
        "Esports tournament.",
        "Giải đấu thể thao điện tử.",
        [],
        [],
        ["pro esports"]
      ),
      v(
        "role-playing",
        "/ˈrəʊl pleɪɪŋ/",
        "/ˈroʊl pleɪɪŋ/",
        "acting as character",
        "nhập vai",
        "noun",
        "Role-playing game (RPG).",
        "Game nhập vai.",
        [],
        [],
        ["tabletop role-playing"]
      ),
      v(
        "quest",
        "/kwest/",
        "/kwest/",
        "mission",
        "nhiệm vụ",
        "noun",
        "Complete the quest.",
        "Hoàn thành nhiệm vụ.",
        ["mission"],
        [],
        ["side quest"]
      ),
    ],
    C1: [
      v(
        "immersion",
        "/ɪˈmɜːʃn/",
        "/ɪˈmɜːrʒn/",
        "deep involvement",
        "sự nhập tâm",
        "noun",
        "Total immersion.",
        "Sự nhập tâm hoàn toàn.",
        ["absorption"],
        [],
        ["game immersion"]
      ),
      v(
        "mechanic",
        "/məˈkænɪk/",
        "/məˈkænɪk/",
        "how game works",
        "cơ chế game",
        "noun",
        "Game mechanics.",
        "Cơ chế trò chơi.",
        [],
        [],
        ["core mechanic"]
      ),
      v(
        "narrative",
        "/ˈnærətɪv/",
        "/ˈnærətɪv/",
        "story",
        "cốt truyện/tường thuật",
        "noun",
        "Strong narrative.",
        "Cốt truyện mạnh.",
        ["story"],
        [],
        ["narrative design"]
      ),
      v(
        "latency",
        "/ˈleɪtənsi/",
        "/ˈleɪtənsi/",
        "lag",
        "độ trễ",
        "noun",
        "Low latency is good.",
        "Độ trễ thấp thì tốt.",
        ["lag"],
        [],
        ["input latency"]
      ),
      v(
        "glitch",
        "/ɡlɪtʃ/",
        "/ɡlɪtʃ/",
        "small error",
        "lỗi kỹ thuật nhỏ",
        "noun",
        "Visual glitch.",
        "Lỗi hình ảnh.",
        ["bug"],
        [],
        ["game glitch"]
      ),
      v(
        "microtransaction",
        "/ˌmaɪkrəʊtrænˈzækʃn/",
        "/ˌmaɪkroʊtrænˈzækʃn/",
        "small payments",
        "giao dịch nhỏ trong game",
        "noun",
        "Avoid microtransactions.",
        "Tránh giao dịch nhỏ.",
        [],
        [],
        ["in-game microtransaction"]
      ),
      v(
        "simulator",
        "/ˈsɪmjuleɪtər/",
        "/ˈsɪmjuleɪtər/",
        "mimic machine",
        "máy mô phỏng",
        "noun",
        "Flight simulator.",
        "Mô phỏng lái máy bay.",
        [],
        [],
        ["racing simulator"]
      ),
      v(
        "achievement",
        "/əˈtʃiːvmənt/",
        "/əˈtʃiːvmənt/",
        "goal reached",
        "thành tựu",
        "noun",
        "Unlock achievement.",
        "Mở khóa thành tựu.",
        ["accomplishment"],
        [],
        ["rare achievement"]
      ),
      v(
        "augmented",
        "/ɔːɡˈmentɪd/",
        "/ɔːɡˈmentɪd/",
        "added to",
        "tăng cường",
        "adjective",
        "Augmented reality.",
        "Thực tế tăng cường (AR).",
        [],
        [],
        ["augmented vision"]
      ),
      v(
        "sandbox",
        "/ˈsændbɒks/",
        "/ˈsændbɑːks/",
        "open worl play",
        "thế giới mở/tự do",
        "noun",
        "Sandbox game.",
        "Game thế giới mở.",
        [],
        [],
        ["sandbox mode"]
      ),
    ],
  },
  Literature: {
    B1: [
      v(
        "novel",
        "/ˈnɒvl/",
        "/ˈnɑːvl/",
        "long story book",
        "tiểu thuyết",
        "noun",
        "Read a novel.",
        "Đọc tiểu thuyết.",
        ["book"],
        [],
        ["classic novel"]
      ),
      v(
        "author",
        "/ˈɔːθər/",
        "/ˈɔːθər/",
        "writer",
        "tác giả",
        "noun",
        "Favorite author.",
        "Tác giả yêu thích.",
        ["writer"],
        [],
        ["famous author"]
      ),
      v(
        "chapter",
        "/ˈtʃæptər/",
        "/ˈtʃæptər/",
        "part of book",
        "chương",
        "noun",
        "Chapter one.",
        "Chương một.",
        ["section"],
        [],
        ["final chapter"]
      ),
      v(
        "fiction",
        "/ˈfɪkʃn/",
        "/ˈfɪkʃn/",
        "not true story",
        "hư cấu",
        "noun",
        "Science fiction.",
        "Khoa học viễn tưởng.",
        ["story"],
        ["non-fiction"],
        ["work of fiction"]
      ),
      v(
        "poetry",
        "/ˈpəʊətri/",
        "/ˈpoʊətri/",
        "poems",
        "thơ ca",
        "noun",
        "Love poetry.",
        "Thơ tình.",
        ["verse"],
        [],
        ["write poetry"]
      ),
      v(
        "poem",
        "/ˈpəʊɪm/",
        "/ˈpoʊəm/",
        "piece of poetry",
        "bài thơ",
        "noun",
        "Read a poem.",
        "Đọc một bài thơ.",
        ["verse"],
        [],
        ["short poem"]
      ),
      v(
        "library",
        "/ˈlaɪbrəri/",
        "/ˈlaɪbreri/",
        "place for books",
        "thư viện",
        "noun",
        "Go to library.",
        "Đến thư viện.",
        [],
        [],
        ["public library"]
      ),
      v(
        "publish",
        "/ˈpʌblɪʃ/",
        "/ˈpʌblɪʃ/",
        "make book available",
        "xuất bản",
        "verb",
        "Publish a book.",
        "Xuất bản sách.",
        ["print"],
        [],
        ["get published"]
      ),
      v(
        "hero",
        "/ˈhɪərəʊ/",
        "/ˈhɪroʊ/",
        "main brave person",
        "người hùng",
        "noun",
        "Comic book hero.",
        "Người hùng truyện tranh.",
        ["protagonist"],
        ["villain"],
        ["super hero"]
      ),
      v(
        "imagination",
        "/ɪˌmædʒɪˈneɪʃn/",
        "/ɪˌmædʒɪˈneɪʃn/",
        "mind creativity",
        "trí tưởng tượng",
        "noun",
        "Use imagination.",
        "Dùng trí tưởng tượng.",
        [],
        [],
        ["vivid imagination"]
      ),
    ],
    B2: [
      v(
        "biography",
        "/baɪˈɒɡrəfi/",
        "/baɪˈɑːɡrəfi/",
        "life story",
        "tiểu sử",
        "noun",
        "Write a biography.",
        "Viết tiểu sử.",
        ["life story"],
        [],
        ["autobiography"]
      ),
      v(
        "mystery",
        "/ˈmɪstri/",
        "/ˈmɪstri/",
        "secret story",
        "bí ẩn/trinh thám",
        "noun",
        "Murder mystery.",
        "Truyện trinh thám giết người.",
        ["puzzle"],
        [],
        ["solve mystery"]
      ),
      v(
        "fantasy",
        "/ˈfæntəsi/",
        "/ˈfæntəsi/",
        "magic story",
        "kỳ ảo",
        "noun",
        "Fantasy novel.",
        "Tiểu thuyết kỳ ảo.",
        [],
        ["reality"],
        ["high fantasy"]
      ),
      v(
        "prose",
        "/prəʊz/",
        "/proʊz/",
        "normal writing",
        "văn xuôi",
        "noun",
        "Poetry and prose.",
        "Thơ và văn xuôi.",
        [],
        ["poetry"],
        ["purple prose"]
      ),
      v(
        "narrative",
        "/ˈnærətɪv/",
        "/ˈnærətɪv/",
        "story telling",
        "tường thuật",
        "noun",
        "First-person narrative.",
        "Kể chuyện ngôi thứ nhất.",
        ["story"],
        [],
        ["narrative style"]
      ),
      v(
        "editor",
        "/ˈedɪtər/",
        "/ˈedɪtər/",
        "person checking text",
        "biên tập viên",
        "noun",
        "Book editor.",
        "Biên tập viên sách.",
        [],
        [],
        ["chief editor"]
      ),
      v(
        "bestseller",
        "/ˌbestˈselər/",
        "/ˌbestˈselər/",
        "very popular book",
        "sách bán chạy",
        "noun",
        "New York Times bestseller.",
        "Sách bán chạy NYT.",
        ["hit"],
        [],
        ["international bestseller"]
      ),
      v(
        "classic",
        "/ˈklæsɪk/",
        "/ˈklæsɪk/",
        "old and good",
        "cổ điển",
        "adjective",
        "Classic literature.",
        "Văn học cổ điển.",
        [],
        [],
        ["modern classic"]
      ),
      v(
        "literacy",
        "/ˈlɪtərəsi/",
        "/ˈlɪtərəsi/",
        "ability to read",
        "biết đọc viết",
        "noun",
        "Literacy rate.",
        "Tỷ lệ biết chữ.",
        [],
        ["illiteracy"],
        ["promote literacy"]
      ),
      v(
        "metaphor",
        "/ˈmetəfə(r)/",
        "/ˈmetəfɔːr/",
        "comparison",
        "phép ẩn dụ",
        "noun",
        "Use a metaphor.",
        "Dùng phép ẩn dụ.",
        [],
        [],
        ["mixed metaphor"]
      ),
    ],
    C2: [
      v(
        "anthology",
        "/ænˈθɒlədʒi/",
        "/ænˈθɑːlədʒi/",
        "collection of writings",
        "tuyển tập",
        "noun",
        "Poetry anthology.",
        "Tuyển tập thơ.",
        ["collection"],
        [],
        ["literary anthology"]
      ),
      v(
        "manuscript",
        "/ˈmænjuskrɪpt/",
        "/ˈmænjuskrɪpt/",
        "unpublished book",
        "bản thảo",
        "noun",
        "Submit manuscript.",
        "Nộp bản thảo.",
        ["draft"],
        [],
        ["original manuscript"]
      ),
      v(
        "pseudonym",
        "/ˈsuːdənɪm/",
        "/ˈsuːdənɪm/",
        "fake name",
        "bút danh",
        "noun",
        "Write under a pseudonym.",
        "Viết dưới bút danh.",
        ["pen name"],
        [],
        ["use pseudonym"]
      ),
      v(
        "critique",
        "/krɪˈtiːk/",
        "/krɪˈtiːk/",
        "detailed analysis",
        "bài phê bình",
        "noun",
        "Literary critique.",
        "Phê bình văn học.",
        ["review"],
        [],
        ["write critique"]
      ),
      v(
        "satire",
        "/ˈsætaɪər/",
        "/ˈsætaɪər/",
        "humor to criticize",
        "châm biếm",
        "noun",
        "Political satire.",
        "Châm biếm chính trị.",
        ["parody"],
        [],
        ["biting satire"]
      ),
      v(
        "allegory",
        "/ˈæləɡəri/",
        "/ˈæləɡɔːri/",
        "story with hidden meaning",
        "truyện ngụ ngôn/ẩn dụ",
        "noun",
        "Political allegory.",
        "Ẩn dụ chính trị.",
        ["symbol"],
        [],
        ["complex allegory"]
      ),
      v(
        "memoir",
        "/ˈmemwɑːr/",
        "/ˈmemwɑːr/",
        "personal record",
        "hồi ký",
        "noun",
        "Write a memoir.",
        "Viết hồi ký.",
        ["autobiography"],
        [],
        ["war memoir"]
      ),
      v(
        "plagiarism",
        "/ˈpleɪdʒərɪzəm/",
        "/ˈpleɪdʒərɪzəm/",
        "copying writing",
        "đạo văn",
        "noun",
        "Accused of plagiarism.",
        "Bị buộc tội đạo văn.",
        ["copying"],
        [],
        ["avoid plagiarism"]
      ),
      v(
        "syntax",
        "/ˈsɪntæks/",
        "/ˈsɪntæks/",
        "sentence structure",
        "cú pháp",
        "noun",
        "Complex syntax.",
        "Cú pháp phức tạp.",
        ["grammar"],
        [],
        ["syntax error"]
      ),
      v(
        "vernacular",
        "/vəˈnækjələ(r)/",
        "/vərˈnækjələr/",
        "everyday language",
        "ngôn ngữ bản địa/bình dân",
        "noun",
        "Local vernacular.",
        "Tiếng địa phương.",
        ["dialect"],
        [],
        ["speak vernacular"]
      ),
    ],
  },
};

// Seed function
async function seedVocab() {
  console.log("🌱 Seeding Vocabulary Data - Entertainment...");

  // Get or create topic group
  const topicGroup = await prisma.topicGroup.upsert({
    where: { name_hubType: { name: "Entertainment", hubType: "vocab" } },
    update: {},
    create: {
      name: "Entertainment",
      order: 6,
      hubType: "vocab",
      subcategories: ["Movies & TV", "Music", "Gaming", "Literature"],
    },
  });

  // Helper to slugify
  const slugify = (text: string) =>
    text.toLowerCase().replace(/&/g, "and").replace(/\s+/g, "-");

  // Iterate over subcategories
  for (const [subcat, levelsData] of Object.entries(entertainmentVocab)) {
    console.log(`Processing Subcategory: ${subcat}`);

    // Iterate over levels
    for (const [level, vocabItems] of Object.entries(levelsData)) {
      const currentLevel = level as Level;
      const items = vocabItems as ReturnType<typeof v>[];

      if (!items || items.length === 0) continue;

      const topicId = `entertainment-${slugify(
        subcat
      )}-${currentLevel.toLowerCase()}`;

      const topic = await prisma.topic.upsert({
        where: { id: topicId },
        update: { wordCount: items.length },
        create: {
          id: topicId,
          title: `${subcat} - ${currentLevel}`,
          subtitle: `Vocabulary about ${subcat.toLowerCase()}`,
          description: `Learn essential vocabulary about ${subcat.toLowerCase()} at ${currentLevel} level.`,
          level: currentLevel,
          wordCount: items.length,
          estimatedTime: Math.ceil(items.length * 2),
          category: "Entertainment",
          subcategory: subcat,
          order: LEVELS.indexOf(currentLevel),
          topicGroupId: topicGroup.id,
        },
      });

      // Seed vocab items
      for (const vocab of items) {
        const vocabId = `${topic.id}-${vocab.word
          .toLowerCase()
          .replace(/\s+/g, "-")}`;
        await prisma.vocabItem.upsert({
          where: { id: vocabId },
          update: vocab,
          create: {
            id: vocabId,
            topicId: topic.id,
            ...vocab,
          },
        });
      }
      console.log(
        `✅ Created: ${subcat} - ${currentLevel} (${items.length} words)`
      );
    }
  }

  console.log("✅ Entertainment seeded successfully!");
}

async function main() {
  try {
    await seedVocab();
  } catch (error) {
    console.error("❌ Error:", error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

main();
