import { PrismaClient, Level, PartOfSpeech } from "@prisma/client";

const prisma = new PrismaClient();

const LEVELS: Level[] = ["A1", "A2", "B1", "B2", "C1", "C2"];

// Helper to create vocab item
const v = (
  word: string,
  phonBr: string,
  phonNAm: string,
  meaning: string,
  vietnameseMeaning: string,
  partOfSpeech: PartOfSpeech,
  exampleSentence: string,
  exampleTranslation: string,
  synonyms: string[] = [],
  antonyms: string[] = [],
  collocations: string[] = []
) => ({
  word,
  phonBr,
  phonNAm,
  meaning,
  vietnameseMeaning,
  partOfSpeech,
  exampleSentence,
  exampleTranslation,
  synonyms,
  antonyms,
  collocations,
});

// ============================================
// TOPIC GROUP 4: TECHNOLOGY
// ============================================

const technologyVocab = {
  Hardware: {
    A1: [
      v(
        "computer",
        "/kəmˈpjuːtər/",
        "/kəmˈpjuːtər/",
        "electronic machine",
        "máy tính",
        "noun",
        "I use a computer.",
        "Tôi dùng máy tính.",
        ["PC"],
        [],
        ["use computer"]
      ),
      v(
        "phone",
        "/fəʊn/",
        "/foʊn/",
        "communication device",
        "điện thoại",
        "noun",
        "My phone is new.",
        "Điện thoại của tôi mới.",
        ["mobile"],
        [],
        ["smart phone"]
      ),
      v(
        "mouse",
        "/maʊs/",
        "/maʊs/",
        "device to move cursor",
        "con chuột",
        "noun",
        "Click the mouse.",
        "Nhấp chuột đi.",
        [],
        [],
        ["computer mouse"]
      ),
      v(
        "screen",
        "/skriːn/",
        "/skriːn/",
        "part showing image",
        "màn hình",
        "noun",
        "The screen is bright.",
        "Màn hình sáng.",
        ["display"],
        [],
        ["touch screen"]
      ),
      v(
        "keyboard",
        "/ˈkiːbɔːd/",
        "/ˈkiːbɔːrd/",
        "keys for typing",
        "bàn phím",
        "noun",
        "Type on the keyboard.",
        "Gõ trên bàn phím.",
        [],
        [],
        ["wireless keyboard"]
      ),
      v(
        "camera",
        "/ˈkæmrə/",
        "/ˈkæmrə/",
        "device taking photos",
        "máy ảnh",
        "noun",
        "Take a photo with camera.",
        "Chụp ảnh bằng máy ảnh.",
        [],
        [],
        ["digital camera"]
      ),
      v(
        "clock",
        "/klɒk/",
        "/klɑːk/",
        "device telling time",
        "đồng hồ",
        "noun",
        "Look at the clock.",
        "Nhìn đồng hồ kìa.",
        [],
        [],
        ["alarm clock"]
      ),
      v(
        "radio",
        "/ˈreɪdiəʊ/",
        "/ˈreɪdioʊ/",
        "audio device",
        "đài radio",
        "noun",
        "Listen to the radio.",
        "Nghe đài.",
        [],
        [],
        ["turn on radio"]
      ),
      v(
        "battery",
        "/ˈbætəri/",
        "/ˈbætəri/",
        "power source",
        "pin",
        "noun",
        "Low battery.",
        "Pin yếu.",
        [],
        [],
        ["change battery"]
      ),
      v(
        "wire",
        "/waɪər/",
        "/waɪər/",
        "metal thread",
        "dây điện",
        "noun",
        "Copper wire.",
        "Dây đồng.",
        ["cable"],
        [],
        ["connect wire"]
      ),
    ],
    B1: [
      v(
        "device",
        "/dɪˈvaɪs/",
        "/dɪˈvaɪs/",
        "piece of equipment",
        "thiết bị",
        "noun",
        "Electronic device.",
        "Thiết bị điện tử.",
        ["gadget"],
        [],
        ["mobile device"]
      ),
      v(
        "laptop",
        "/ˈlæptɒp/",
        "/ˈlæptɑːp/",
        "portable computer",
        "máy tính xách tay",
        "noun",
        "Open your laptop.",
        "Mở laptop ra.",
        ["notebook"],
        ["desktop"],
        ["gaming laptop"]
      ),
      v(
        "tablet",
        "/ˈtæblət/",
        "/ˈtæblət/",
        "flat computer",
        "máy tính bảng",
        "noun",
        "Use a tablet.",
        "Dùng máy tính bảng.",
        ["pad"],
        [],
        ["graphics tablet"]
      ),
      v(
        "charger",
        "/ˈtʃɑːdʒər/",
        "/ˈtʃɑːrdʒər/",
        "device to power battery",
        "cục sạc",
        "noun",
        "Where is my charger?",
        "Sạc của tôi đâu?",
        [],
        [],
        ["phone charger"]
      ),
      v(
        "printer",
        "/ˈprɪntər/",
        "/ˈprɪntər/",
        "machine for printing",
        "máy in",
        "noun",
        "The printer is out of ink.",
        "Máy in hết mực.",
        [],
        [],
        ["laser printer"]
      ),
      v(
        "cable",
        "/ˈkeɪbl/",
        "/ˈkeɪbl/",
        "thick wire",
        "dây cáp",
        "noun",
        "Connect the cable.",
        "Cắm dây cáp vào.",
        ["cord"],
        [],
        ["power cable"]
      ),
      v(
        "memory",
        "/ˈmeməri/",
        "/ˈmeməri/",
        "storage space",
        "bộ nhớ",
        "noun",
        "Full memory.",
        "Bộ nhớ đầy.",
        ["storage"],
        [],
        ["memory card"]
      ),
      v(
        "switch",
        "/swɪtʃ/",
        "/swɪtʃ/",
        "button to turn on/off",
        "công tắc",
        "noun",
        "Flip the switch.",
        "Bật công tắc.",
        [],
        [],
        ["light switch"]
      ),
      v(
        "plug",
        "/plʌɡ/",
        "/plʌɡ/",
        "connector for electricity",
        "phích cắm",
        "noun",
        "Pull the plug.",
        "Rút phích cắm.",
        [],
        [],
        ["smart plug"]
      ),
      v(
        "disk",
        "/dɪsk/",
        "/dɪsk/",
        "storage object",
        "đĩa",
        "noun",
        "Save to disk.",
        "Lưu vào đĩa.",
        [],
        [],
        ["hard disk"]
      ),
    ],
    C2: [
      v(
        "microprocessor",
        "/ˌmaɪkrəʊˈprəʊsesər/",
        "/ˌmaɪkroʊˈprɑːsesər/",
        "computer chip",
        "bộ vi xử lý",
        "noun",
        "Fast microprocessor.",
        "Vi xử lý nhanh.",
        ["chip"],
        [],
        ["silicon microprocessor"]
      ),
      v(
        "circuit",
        "/ˈsɜːkɪt/",
        "/ˈsɜːrkɪt/",
        "path for electricity",
        "mạch điện",
        "noun",
        "Short circuit.",
        "Chập mạch.",
        [],
        [],
        ["integrated circuit"]
      ),
      v(
        "peripheral",
        "/pəˈrɪfərəl/",
        "/pəˈrɪfərəl/",
        "external device",
        "thiết bị ngoại vi",
        "noun",
        "Connect peripherals.",
        "Kết nối thiết bị ngoại vi.",
        ["accessory"],
        [],
        ["computer peripheral"]
      ),
      v(
        "motherboard",
        "/ˈmʌðəbɔːd/",
        "/ˈmʌðərbɔːrd/",
        "main circuit board",
        "bo mạch chủ",
        "noun",
        "Replace the motherboard.",
        "Thay bo mạch chủ.",
        ["mainboard"],
        [],
        ["gaming motherboard"]
      ),
      v(
        "semiconductor",
        "/ˌsemikənˈdʌktər/",
        "/ˌsemikənˈdʌktər/",
        "material for chips",
        "chất bán dẫn",
        "noun",
        "Semiconductor industry.",
        "Công nghiệp bán dẫn.",
        [],
        [],
        ["semiconductor chip"]
      ),
      v(
        "configuration",
        "/kənˌfɪɡəˈreɪʃn/",
        "/kənˌfɪɡjəˈreɪʃn/",
        "arrangement of parts",
        "cấu hình",
        "noun",
        "System configuration.",
        "Cấu hình hệ thống.",
        ["setup"],
        [],
        ["default configuration"]
      ),
      v(
        "apparatus",
        "/ˌæpəˈreɪtəs/",
        "/ˌæpəˈrætəs/",
        "technical equipment",
        "thiết bị/dụng cụ",
        "noun",
        "Breathing apparatus.",
        "Thiết bị trợ thở.",
        ["equipment"],
        [],
        ["scientific apparatus"]
      ),
      v(
        "obsolescence",
        "/ˌɒbsəˈlesns/",
        "/ˌɑːbsəˈlesns/",
        "becoming outdated",
        "sự lỗi thời",
        "noun",
        "Planned obsolescence.",
        "Sự lỗi thời có tính toán.",
        [],
        [],
        ["technological obsolescence"]
      ),
      v(
        "sensor",
        "/ˈsensər/",
        "/ˈsensər/",
        "detecting device",
        "cảm biến",
        "noun",
        "Motion sensor.",
        "Cảm biến chuyển động.",
        [],
        [],
        ["temperature sensor"]
      ),
      v(
        "prototype",
        "/ˈprəʊtətaɪp/",
        "/ˈproʊtətaɪp/",
        "first model",
        "nguyên mẫu",
        "noun",
        "Build a prototype.",
        "Xây dựng nguyên mẫu.",
        ["model"],
        [],
        ["working prototype"]
      ),
    ],
  },
  Software: {
    A2: [
      v(
        "app",
        "/æp/",
        "/æp/",
        "application program",
        "ứng dụng",
        "noun",
        "Download an app.",
        "Tải ứng dụng.",
        ["program"],
        [],
        ["mobile app"]
      ),
      v(
        "file",
        "/faɪl/",
        "/faɪl/",
        "stored data",
        "tập tin",
        "noun",
        "Open the file.",
        "Mở tập tin.",
        [],
        [],
        ["save file"]
      ),
      v(
        "game",
        "/ɡeɪm/",
        "/ɡeɪm/",
        "play activity",
        "trò chơi",
        "noun",
        "Play a video game.",
        "Chơi điện tử.",
        [],
        [],
        ["online game"]
      ),
      v(
        "click",
        "/klɪk/",
        "/klɪk/",
        "press mouse button",
        "nhấn chuột",
        "verb",
        "Click here.",
        "Nhấn vào đây.",
        ["press"],
        [],
        ["double click"]
      ),
      v(
        "save",
        "/seɪv/",
        "/seɪv/",
        "keep data",
        "lưu",
        "verb",
        "Save your work.",
        "Lưu công việc của bạn.",
        ["store"],
        ["delete"],
        ["save button"]
      ),
      v(
        "open",
        "/ˈəʊpən/",
        "/ˈoʊpən/",
        "start a program",
        "mở",
        "verb",
        "Open the window.",
        "Mở cửa sổ.",
        ["start"],
        ["close"],
        ["open files"]
      ),
      v(
        "close",
        "/kləʊz/",
        "/kloʊz/",
        "end a program",
        "đóng",
        "verb",
        "Close the app.",
        "Đóng ứng dụng.",
        ["shut"],
        ["open"],
        ["close program"]
      ),
      v(
        "code",
        "/kəʊd/",
        "/koʊd/",
        "program instructions",
        "mã",
        "noun",
        "Write code.",
        "Viết mã.",
        [],
        [],
        ["source code"]
      ),
      v(
        "data",
        "/ˈdeɪtə/",
        "/ˈdeɪtə/",
        "information",
        "dữ liệu",
        "noun",
        "Big data.",
        "Dữ liệu lớn.",
        ["info"],
        [],
        ["personal data"]
      ),
      v(
        "text",
        "/tekst/",
        "/tekst/",
        "written words",
        "văn bản",
        "noun",
        "Send a text.",
        "Gửi tin nhắn.",
        [],
        [],
        ["text message"]
      ),
    ],
    B2: [
      v(
        "install",
        "/ɪnˈstɔːl/",
        "/ɪnˈstɔːl/",
        "put software on computer",
        "cài đặt",
        "verb",
        "Install the update.",
        "Cài bản cập nhật.",
        ["setup"],
        ["uninstall"],
        ["install software"]
      ),
      v(
        "update",
        "/ʌpˈdeɪt/",
        "/ˌʌpˈdeɪt/",
        "make new",
        "cập nhật",
        "verb",
        "Update your system.",
        "Cập nhật hệ thống.",
        ["upgrade"],
        [],
        ["security update"]
      ),
      v(
        "virus",
        "/ˈvaɪrəs/",
        "/ˈvaɪrəs/",
        "bad program",
        "vi-rút",
        "noun",
        "Anti-virus software.",
        "Phần mềm diệt vi-rút.",
        ["malware"],
        [],
        ["computer virus"]
      ),
      v(
        "interface",
        "/ˈɪntəfeɪs/",
        "/ˈɪntərfeɪs/",
        "what you see on screen",
        "giao diện",
        "noun",
        "User interface (UI).",
        "Giao diện người dùng.",
        [],
        [],
        ["friendly interface"]
      ),
      v(
        "database",
        "/ˈdeɪtəbeɪs/",
        "/ˈdeɪtəbeɪs/",
        "collection of data",
        "cơ sở dữ liệu",
        "noun",
        "Search the database.",
        "Tìm trong cơ sở dữ liệu.",
        [],
        [],
        ["database management"]
      ),
      v(
        "platform",
        "/ˈplætfɔːm/",
        "/ˈplætfɔːrm/",
        "operating system/env",
        "nền tảng",
        "noun",
        "Cross-platform app.",
        "Ứng dụng đa nền tảng.",
        [],
        [],
        ["digital platform"]
      ),
      v(
        "bug",
        "/bʌɡ/",
        "/bʌɡ/",
        "error in code",
        "lỗi phần mềm",
        "noun",
        "Fix a bug.",
        "Sửa lỗi.",
        ["error"],
        [],
        ["software bug"]
      ),
      v(
        "browse",
        "/braʊz/",
        "/braʊz/",
        "look through",
        "duyệt",
        "verb",
        "Browse files.",
        "Duyệt tập tin.",
        ["search"],
        [],
        ["browse internet"]
      ),
      v(
        "delete",
        "/dɪˈliːt/",
        "/dɪˈliːt/",
        "remove",
        "xóa",
        "verb",
        "Delete this file.",
        "Xóa tập tin này.",
        ["remove"],
        ["restore"],
        ["delete account"]
      ),
      v(
        "edit",
        "/ˈedɪt/",
        "/ˈedɪt/",
        "change",
        "chỉnh sửa",
        "verb",
        "Edit the photo.",
        "Chỉnh sửa ảnh.",
        ["modify"],
        [],
        ["edit video"]
      ),
    ],
    C1: [
      v(
        "algorithm",
        "/ˈælɡərɪðəm/",
        "/ˈælɡərɪðəm/",
        "set of rules",
        "thuật toán",
        "noun",
        "Search algorithm.",
        "Thuật toán tìm kiếm.",
        [],
        [],
        ["complex algorithm"]
      ),
      v(
        "encryption",
        "/ɪnˈkrɪpʃn/",
        "/ɪnˈkrɪpʃn/",
        "hiding data",
        "mã hóa",
        "noun",
        "End-to-end encryption.",
        "Mã hóa đầu cuối.",
        [],
        [],
        ["data encryption"]
      ),
      v(
        "protocol",
        "/ˈprəʊtəkɒl/",
        "/ˈproʊtəkɑːl/",
        "rules for connection",
        "giao thức",
        "noun",
        "Internet protocol.",
        "Giao thức Internet.",
        [],
        [],
        ["security protocol"]
      ),
      v(
        "integration",
        "/ˌɪntɪˈɡreɪʃn/",
        "/ˌɪntɪˈɡreɪʃn/",
        "combining systems",
        "sự tích hợp",
        "noun",
        "System integration.",
        "Tích hợp hệ thống.",
        [],
        [],
        ["seamless integration"]
      ),
      v(
        "deployment",
        "/dɪˈplɔɪmənt/",
        "/dɪˈplɔɪmənt/",
        "releasing software",
        "triển khai",
        "noun",
        "Software deployment.",
        "Triển khai phần mềm.",
        ["release"],
        [],
        ["rapid deployment"]
      ),
      v(
        "optimization",
        "/ˌɒptɪmaɪˈzeɪʃn/",
        "/ˌɑːptɪməˈzeɪʃn/",
        "making best",
        "tối ưu hóa",
        "noun",
        "SEO optimization.",
        "Tối ưu hóa SEO.",
        ["improvement"],
        [],
        ["performance optimization"]
      ),
      v(
        "compatibility",
        "/kəmˌpætəˈbɪləti/",
        "/kəmˌpætəˈbɪləti/",
        "working together",
        "khả năng tương thích",
        "noun",
        "Check compatibility.",
        "Kiểm tra tương thích.",
        [],
        [],
        ["backward compatibility"]
      ),
      v(
        "virtualization",
        "/ˌvɜːtʃuəlaɪˈzeɪʃn/",
        "/ˌvɜːrtʃuələˈzeɪʃn/",
        "creating virtual version",
        "ảo hóa",
        "noun",
        "Server virtualization.",
        "Ảo hóa máy chủ.",
        [],
        [],
        ["hardware virtualization"]
      ),
      v(
        "firmware",
        "/ˈfɜːmweər/",
        "/ˈfɜːrmwer/",
        "permanent software",
        "phần mềm hệ thống",
        "noun",
        "Update firmware.",
        "Cập nhật firmware.",
        [],
        [],
        ["device firmware"]
      ),
      v(
        "backend",
        "/ˌbækˈend/",
        "/ˌbækˈend/",
        "server side",
        "hậu trường/backend",
        "noun",
        "Backend developer.",
        "Lập trình viên backend.",
        [],
        ["frontend"],
        ["backend system"]
      ),
    ],
  },
  Internet: {
    A1: [
      v(
        "wifi",
        "/ˈwaɪ faɪ/",
        "/ˈwaɪ faɪ/",
        "wireless internet",
        "wifi",
        "noun",
        "Free wifi.",
        "Wifi miễn phí.",
        [],
        [],
        ["connect wifi"]
      ),
      v(
        "link",
        "/lɪŋk/",
        "/lɪŋk/",
        "connection to click",
        "liên kết",
        "noun",
        "Click the link.",
        "Nhấn vào liên kết.",
        [],
        [],
        ["web link"]
      ),
      v(
        "chat",
        "/tʃæt/",
        "/tʃæt/",
        "talk online",
        "trò chuyện",
        "verb",
        "Chat with friends.",
        "Trò chuyện với bạn.",
        [],
        [],
        ["online chat"]
      ),
      v(
        "post",
        "/pəʊst/",
        "/poʊst/",
        "put online",
        "đăng bài",
        "verb",
        "Post a photo.",
        "Đăng ảnh.",
        [],
        [],
        ["blog post"]
      ),
      v(
        "page",
        "/peɪdʒ/",
        "/peɪdʒ/",
        "part of website",
        "trang",
        "noun",
        "Go to next page.",
        "Sang trang tiếp.",
        [],
        [],
        ["web page"]
      ),
      v(
        "search",
        "/sɜːtʃ/",
        "/sɜːrtʃ/",
        "look for",
        "tìm kiếm",
        "verb",
        "Search Google.",
        "Tìm trên Google.",
        ["find"],
        [],
        ["search engine"]
      ),
      v(
        "send",
        "/send/",
        "/send/",
        "make go",
        "gửi",
        "verb",
        "Send a message.",
        "Gửi tin nhắn.",
        ["dispatch"],
        ["receive"],
        ["send email"]
      ),
      v(
        "online",
        "/ˌɒnˈlaɪn/",
        "/ˌɑːnˈlaɪn/",
        "connected",
        "trực tuyến",
        "adjective",
        "I am online.",
        "Tôi đang trực tuyến.",
        ["connected"],
        ["offline"],
        ["shop online"]
      ),
      v(
        "web",
        "/web/",
        "/web/",
        "internet",
        "mạng",
        "noun",
        "Surf the web.",
        "Lướt mạng.",
        ["internet"],
        [],
        ["world wide web"]
      ),
      v(
        "site",
        "/saɪt/",
        "/saɪt/",
        "place on web",
        "trang web",
        "noun",
        "Visit the site.",
        "Ghé thăm trang web.",
        ["website"],
        [],
        ["web site"]
      ),
    ],
    B1: [
      v(
        "browser",
        "/ˈbraʊzər/",
        "/ˈbraʊzər/",
        "program to view web",
        "trình duyệt",
        "noun",
        "Open browser.",
        "Mở trình duyệt.",
        [],
        [],
        ["web browser"]
      ),
      v(
        "download",
        "/ˌdaʊnˈləʊd/",
        "/ˌdaʊnˈloʊd/",
        "get from internet",
        "tải xuống",
        "verb",
        "Download the movie.",
        "Tải phim.",
        [],
        ["upload"],
        ["free download"]
      ),
      v(
        "upload",
        "/ˌʌpˈləʊd/",
        "/ˌʌpˈloʊd/",
        "put on internet",
        "tải lên",
        "verb",
        "Upload video.",
        "Tải video lên.",
        [],
        ["download"],
        ["upload file"]
      ),
      v(
        "password",
        "/ˈpɑːswɜːd/",
        "/ˈpæswɜːrd/",
        "secret code",
        "mật khẩu",
        "noun",
        "Enter password.",
        "Nhập mật khẩu.",
        [],
        [],
        ["strong password"]
      ),
      v(
        "network",
        "/ˈnetwɜːk/",
        "/ˈnetwɜːrk/",
        "connected computers",
        "mạng lưới",
        "noun",
        "Social network.",
        "Mạng xã hội.",
        [],
        [],
        ["secure network"]
      ),
      v(
        "signal",
        "/ˈsɪɡnəl/",
        "/ˈsɪɡnəl/",
        "connection strength",
        "tín hiệu",
        "noun",
        "Weak signal.",
        "Tín hiệu yếu.",
        [],
        [],
        ["lost signal"]
      ),
      v(
        "connect",
        "/kəˈnekt/",
        "/kəˈnekt/",
        "join",
        "kết nối",
        "verb",
        "Connect to internet.",
        "Kết nối internet.",
        ["link"],
        ["disconnect"],
        ["auto connect"]
      ),
      v(
        "blog",
        "/blɒɡ/",
        "/blɑːɡ/",
        "online diary",
        "blog/nhật ký mạng",
        "noun",
        "Write a blog.",
        "Viết blog.",
        [],
        [],
        ["travel blog"]
      ),
      v(
        "comment",
        "/ˈkɒment/",
        "/ˈkɑːment/",
        "opinion written",
        "bình luận",
        "noun",
        "Leave a comment.",
        "Để lại bình luận.",
        [],
        [],
        ["post comment"]
      ),
      v(
        "account",
        "/əˈkaʊnt/",
        "/əˈkaʊnt/",
        "membership",
        "tài khoản",
        "noun",
        "Create an account.",
        "Tạo tài khoản.",
        [],
        [],
        ["user account"]
      ),
    ],
    C2: [
      v(
        "latency",
        "/ˈleɪtənsi/",
        "/ˈleɪtənsi/",
        "delay in data",
        "độ trễ",
        "noun",
        "Low latency.",
        "Độ trễ thấp.",
        ["delay"],
        [],
        ["network latency"]
      ),
      v(
        "cybersecurity",
        "/ˌsaɪbəsɪˈkjʊərəti/",
        "/ˌsaɪbərsɪˈkjʊərəti/",
        "online safety",
        "an ninh mạng",
        "noun",
        "Cybersecurity expert.",
        "Chuyên gia an ninh mạng.",
        [],
        [],
        ["improve cybersecurity"]
      ),
      v(
        "authentication",
        "/ɔːˌθentɪˈkeɪʃn/",
        "/ɔːˌθentɪˈkeɪʃn/",
        "proving identity",
        "xác thực",
        "noun",
        "Two-factor authentication.",
        "Xác thực hai yếu tố.",
        ["verification"],
        [],
        ["user authentication"]
      ),
      v(
        "bandwidth",
        "/ˈbændwɪdθ/",
        "/ˈbændwɪdθ/",
        "capacity of network",
        "băng thông",
        "noun",
        "High bandwidth.",
        "Băng thông cao.",
        [],
        [],
        ["limit bandwidth"]
      ),
      v(
        "surveillance",
        "/sɜːˈveɪləns/",
        "/sɜːrˈveɪləns/",
        "watching",
        "giám sát",
        "noun",
        "Mass surveillance.",
        "Giám sát hàng loạt.",
        ["monitoring"],
        [],
        ["digital surveillance"]
      ),
      v(
        "censorship",
        "/ˈsensəʃɪp/",
        "/ˈsensərʃɪp/",
        "blocking content",
        "kiểm duyệt",
        "noun",
        "Internet censorship.",
        "Kiểm duyệt internet.",
        [],
        [],
        ["avoid censorship"]
      ),
      v(
        "decentralization",
        "/ˌdiːsentrəlaɪˈzeɪʃn/",
        "/ˌdiːsentrəlaɪˈzeɪʃn/",
        "no central control",
        "phi tập trung",
        "noun",
        "Decentralization of power.",
        "Sự phi tập trung hóa quyền lực.",
        [],
        ["centralization"],
        ["network decentralization"]
      ),
      v(
        "encryption",
        "/ɪnˈkrɪpʃn/",
        "/ɪnˈkrɪpʃn/",
        "coding data",
        "mã hóa",
        "noun",
        "Strong encryption.",
        "Mã hóa mạnh.",
        [],
        [],
        ["file encryption"]
      ),
      v(
        "phishing",
        "/ˈfɪʃɪŋ/",
        "/ˈfɪʃɪŋ/",
        "stealing info scam",
        "tấn công giả mạo",
        "noun",
        "Phishing email.",
        "Email giả mạo.",
        [],
        [],
        ["phishing attack"]
      ),
      v(
        "domain",
        "/dəˈmeɪn/",
        "/doʊˈmeɪn/",
        "web address owner",
        "tên miền",
        "noun",
        "Buy a domain.",
        "Mua tên miền.",
        [],
        [],
        ["public domain"]
      ),
    ],
  },
  AI: {
    B1: [
      v(
        "robot",
        "/ˈrəʊbɒt/",
        "/ˈroʊbɑːt/",
        "machine acting like human",
        "rô-bốt",
        "noun",
        "Smart robot.",
        "Người máy thông minh.",
        ["machine"],
        [],
        ["robot arm"]
      ),
      v(
        "smart",
        "/smɑːt/",
        "/smɑːrt/",
        "clever/AI",
        "thông minh",
        "adjective",
        "Smart home.",
        "Nhà thông minh.",
        ["intelligent"],
        ["stupid"],
        ["smart device"]
      ),
      v(
        "future",
        "/ˈfjuːtʃər/",
        "/ˈfjuːtʃər/",
        "time coming",
        "tương lai",
        "noun",
        "AI is the future.",
        "AI là tương lai.",
        [],
        ["past"],
        ["near future"]
      ),
      v(
        "machine",
        "/məˈʃiːn/",
        "/məˈʃiːn/",
        "mechanical device",
        "máy móc",
        "noun",
        "Machine learning.",
        "Máy học.",
        [],
        [],
        ["powerful machine"]
      ),
      v(
        "learn",
        "/lɜːn/",
        "/lɜːrn/",
        "get knowledge",
        "học",
        "verb",
        "Machines can learn.",
        "Máy móc có thể học.",
        ["study"],
        [],
        ["learn fast"]
      ),
      v(
        "voice",
        "/vɔɪs/",
        "/vɔɪs/",
        "sound from mouth",
        "giọng nói",
        "noun",
        "Voice recognition.",
        "Nhận diện giọng nói.",
        [],
        [],
        ["human voice"]
      ),
      v(
        "tool",
        "/tuːl/",
        "/tuːl/",
        "something helping work",
        "công cụ",
        "noun",
        "AI tool.",
        "Công cụ AI.",
        ["instrument"],
        [],
        ["useful tool"]
      ),
      v(
        "system",
        "/ˈsɪstəm/",
        "/ˈsɪstəm/",
        "set of parts",
        "hệ thống",
        "noun",
        "Computer system.",
        "Hệ thống máy tính.",
        [],
        [],
        ["complex system"]
      ),
      v(
        "automatic",
        "/ˌɔːtəˈmætɪk/",
        "/ˌɔːtəˈmætɪk/",
        "working by itself",
        "tự động",
        "adjective",
        "Automatic car.",
        "Xe tự động.",
        ["automated"],
        ["manual"],
        ["fully automatic"]
      ),
      v(
        "data",
        "/ˈdeɪtə/",
        "/ˈdeɪtə/",
        "info for computer",
        "dữ liệu",
        "noun",
        "Collect data.",
        "Thu thập dữ liệu.",
        [],
        [],
        ["process data"]
      ),
    ],
    B2: [
      v(
        "intelligence",
        "/ɪnˈtelɪdʒəns/",
        "/ɪnˈtelɪdʒəns/",
        "ability to think",
        "trí tuệ",
        "noun",
        "Artificial Intelligence.",
        "Trí tuệ nhân tạo.",
        [],
        [],
        ["high intelligence"]
      ),
      v(
        "prediction",
        "/prɪˈdɪkʃn/",
        "/prɪˈdɪkʃn/",
        "saying future",
        "dự đoán",
        "noun",
        "Make a prediction.",
        "Đưa ra dự đoán.",
        ["forecast"],
        [],
        ["accurate prediction"]
      ),
      v(
        "analysis",
        "/əˈnælɪsɪs/",
        "/əˈnælɪsɪs/",
        "detailed study",
        "phân tích",
        "noun",
        "Data analysis.",
        "Phân tích dữ liệu.",
        [],
        [],
        ["deep analysis"]
      ),
      v(
        "automation",
        "/ˌɔːtəˈmeɪʃn/",
        "/ˌɔːtəˈmeɪʃn/",
        "using machines",
        "tự động hóa",
        "noun",
        "Home automation.",
        "Tự động hóa nhà cửa.",
        [],
        [],
        ["process automation"]
      ),
      v(
        "virtual",
        "/ˈvɜːtʃuəl/",
        "/ˈvɜːrtʃuəl/",
        "not real/computer",
        "ảo",
        "adjective",
        "Virtual assistant.",
        "Trợ lý ảo.",
        [],
        ["real"],
        ["virtual reality"]
      ),
      v(
        "recognition",
        "/ˌrekəɡˈnɪʃn/",
        "/ˌrekəɡˈnɪʃn/",
        "knowing again",
        "nhận diện",
        "noun",
        "Facial recognition.",
        "Nhận diện khuôn mặt.",
        [],
        [],
        ["voice recognition"]
      ),
      v(
        "logic",
        "/ˈlɒdʒɪk/",
        "/ˈlɑːdʒɪk/",
        "sensible thinking",
        "logic",
        "noun",
        "Computer logic.",
        "Logic máy tính.",
        [],
        [],
        ["logic gate"]
      ),
      v(
        "pattern",
        "/ˈpætn/",
        "/ˈpætərn/",
        "repeated shape/event",
        "mô hình/mẫu",
        "noun",
        "Find a pattern.",
        "Tìm quy luật/mẫu.",
        [],
        [],
        ["pattern recognition"]
      ),
      v(
        "complex",
        "/ˈkɒmpleks/",
        "/kəmˈpleks/",
        "not simple",
        "phức tạp",
        "adjective",
        "Complex problem.",
        "Vấn đề phức tạp.",
        ["complicated"],
        ["simple"],
        ["complex system"]
      ),
      v(
        "interact",
        "/ˌɪntərˈækt/",
        "/ˌɪntərˈækt/",
        "communicate with",
        "tương tác",
        "verb",
        "Interact with AI.",
        "Tương tác với AI.",
        [],
        [],
        ["interact daily"]
      ),
    ],
    C1: [
      v(
        "neural",
        "/ˈnjʊərəl/",
        "/ˈnʊrəl/",
        "related to nerves",
        "thuộc thần kinh",
        "adjective",
        "Neural network.",
        "Mạng nơ-ron.",
        [],
        [],
        ["neural pathway"]
      ),
      v(
        "cognitive",
        "/ˈkɒɡnətɪv/",
        "/ˈkɑːɡnətɪv/",
        "mental process",
        "nhận thức",
        "adjective",
        "Cognitive computing.",
        "Điện toán nhận thức.",
        [],
        [],
        ["cognitive ability"]
      ),
      v(
        "autonomous",
        "/ɔːˈtɒnəməs/",
        "/ɔːˈtɑːnəməs/",
        "self-governing",
        "tự hành",
        "adjective",
        "Autonomous vehicle.",
        "Xe tự hành.",
        ["independent"],
        [],
        ["fully autonomous"]
      ),
      v(
        "simulation",
        "/ˌsɪmjuˈleɪʃn/",
        "/ˌsɪmjuˈleɪʃn/",
        "imitation of real",
        "mô phỏng",
        "noun",
        "Run a simulation.",
        "Chạy mô phỏng.",
        [],
        [],
        ["computer simulation"]
      ),
      v(
        "perception",
        "/pəˈsepʃn/",
        "/pərˈsepʃn/",
        "way of seeing",
        "sự nhận thức",
        "noun",
        "Machine perception.",
        "Nhận thức máy.",
        [],
        [],
        ["visual perception"]
      ),
      v(
        "ethics",
        "/ˈeθɪks/",
        "/ˈeθɪks/",
        "moral rules",
        "đạo đức",
        "noun",
        "AI ethics.",
        "Đạo đức AI.",
        ["morality"],
        [],
        ["code of ethics"]
      ),
      v(
        "bias",
        "/ˈbaɪəs/",
        "/ˈbaɪəs/",
        "unfair preference",
        "thiên kiến",
        "noun",
        "Algorithmic bias.",
        "Thiên kiến thuật toán.",
        ["prejudice"],
        [],
        ["unconscious bias"]
      ),
      v(
        "computational",
        "/ˌkɒmpjuˈteɪʃənl/",
        "/ˌkɑːmpjuˈteɪʃənl/",
        "calculating",
        "tính toán",
        "adjective",
        "Computational power.",
        "Sức mạnh tính toán.",
        [],
        [],
        ["computational model"]
      ),
      v(
        "generative",
        "/ˈdʒenərətɪv/",
        "/ˈdʒenərətɪv/",
        "able to produce",
        "tạo sinh",
        "adjective",
        "Generative AI.",
        "AI tạo sinh.",
        [],
        [],
        ["generative model"]
      ),
      v(
        "singularity",
        "/ˌsɪŋɡjuˈlærəti/",
        "/ˌsɪŋɡjuˈlærəti/",
        "point of infinite change",
        "điểm kỳ dị",
        "noun",
        "Technological singularity.",
        "Điểm kỳ dị công nghệ.",
        [],
        [],
        ["reach singularity"]
      ),
    ],
  },
};

// Seed function
async function seedVocab() {
  console.log("🌱 Seeding Vocabulary Data - Technology...");

  // Get or create topic group
  const topicGroup = await prisma.topicGroup.upsert({
    where: { name_hubType: { name: "Technology", hubType: "vocab" } },
    update: {},
    create: {
      name: "Technology",
      order: 4,
      hubType: "vocab",
      subcategories: ["Hardware", "Software", "Internet", "AI"],
    },
  });

  // Helper to slugify
  const slugify = (text: string) =>
    text.toLowerCase().replace(/&/g, "and").replace(/\s+/g, "-");

  // Iterate over subcategories
  for (const [subcat, levelsData] of Object.entries(technologyVocab)) {
    console.log(`Processing Subcategory: ${subcat}`);

    // Iterate over levels
    for (const [level, vocabItems] of Object.entries(levelsData)) {
      const currentLevel = level as Level;
      const items = vocabItems as ReturnType<typeof v>[];

      if (!items || items.length === 0) continue;

      const topicId = `technology-${slugify(
        subcat
      )}-${currentLevel.toLowerCase()}`;

      const topic = await prisma.topic.upsert({
        where: { id: topicId },
        update: { wordCount: items.length },
        create: {
          id: topicId,
          title: `${subcat} - ${currentLevel}`,
          subtitle: `Vocabulary about ${subcat.toLowerCase()}`,
          description: `Learn essential vocabulary about ${subcat.toLowerCase()} at ${currentLevel} level.`,
          level: currentLevel,
          wordCount: items.length,
          estimatedTime: Math.ceil(items.length * 2),
          category: "Technology",
          subcategory: subcat,
          order: LEVELS.indexOf(currentLevel),
          topicGroupId: topicGroup.id,
        },
      });

      // Seed vocab items
      for (const vocab of items) {
        const vocabId = `${topic.id}-${vocab.word
          .toLowerCase()
          .replace(/\s+/g, "-")}`;
        await prisma.vocabItem.upsert({
          where: { id: vocabId },
          update: vocab,
          create: {
            id: vocabId,
            topicId: topic.id,
            ...vocab,
          },
        });
      }
      console.log(
        `✅ Created: ${subcat} - ${currentLevel} (${items.length} words)`
      );
    }
  }

  console.log("✅ Technology seeded successfully!");
}

async function main() {
  try {
    await seedVocab();
  } catch (error) {
    console.error("❌ Error:", error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

main();
