import { PrismaClient, Level, PartOfSpeech } from "@prisma/client";

const prisma = new PrismaClient();

const LEVELS: Level[] = ["A1", "A2", "B1", "B2", "C1", "C2"];

// Helper to create vocab item
const v = (
  word: string,
  phonBr: string,
  phonNAm: string,
  meaning: string,
  vietnameseMeaning: string,
  partOfSpeech: PartOfSpeech,
  exampleSentence: string,
  exampleTranslation: string,
  synonyms: string[] = [],
  antonyms: string[] = [],
  collocations: string[] = []
) => ({
  word,
  phonBr,
  phonNAm,
  meaning,
  vietnameseMeaning,
  partOfSpeech,
  exampleSentence,
  exampleTranslation,
  synonyms,
  antonyms,
  collocations,
});

// ============================================
// TOPIC GROUP 2: WORK & CAREER
// ============================================

const workCareerVocab = {
  "Office Basics": {
    A1: [
      v(
        "office",
        "/ˈɒfɪs/",
        "/ˈɑːfɪs/",
        "place for work",
        "văn phòng",
        "noun",
        "I work in an office.",
        "Tôi làm việc ở văn phòng.",
        ["workplace"],
        [],
        ["office worker"]
      ),
      v(
        "desk",
        "/desk/",
        "/desk/",
        "table for work",
        "bàn làm việc",
        "noun",
        "My desk is clean.",
        "Bàn của tôi sạch sẽ.",
        ["table"],
        [],
        ["office desk"]
      ),
      v(
        "boss",
        "/bɒs/",
        "/bɔːs/",
        "person in charge",
        "sếp",
        "noun",
        "My boss is nice.",
        "Sếp tôi tốt bụng.",
        ["manager"],
        ["employee"],
        ["big boss"]
      ),
      v(
        "email",
        "/ˈiːmeɪl/",
        "/ˈiːmeɪl/",
        "electronic letter",
        "thư điện tử",
        "noun",
        "Send me an email.",
        "Gửi email cho tôi.",
        [],
        [],
        ["send email"]
      ),
      v(
        "call",
        "/kɔːl/",
        "/kɔːl/",
        "speak on phone",
        "gọi điện",
        "verb",
        "Call me later.",
        "Gọi tôi sau nhé.",
        ["phone"],
        [],
        ["phone call"]
      ),
      v(
        "paper",
        "/ˈpeɪpər/",
        "/ˈpeɪpər/",
        "material for writing",
        "giấy",
        "noun",
        "I need some paper.",
        "Tôi cần ít giấy.",
        [],
        [],
        ["white paper"]
      ),
      v(
        "pen",
        "/pen/",
        "/pen/",
        "tool for writing",
        "cây bút",
        "noun",
        "Do you have a pen?",
        "Bạn có bút không?",
        [],
        [],
        ["blue pen"]
      ),
      v(
        "computer",
        "/kəmˈpjuːtər/",
        "/kəmˈpjuːtər/",
        "electronic machine",
        "máy tính",
        "noun",
        "I use a computer.",
        "Tôi dùng máy tính.",
        ["PC"],
        [],
        ["laptop computer"]
      ),
      v(
        "job",
        "/dʒɒb/",
        "/dʒɑːb/",
        "work you do",
        "công việc",
        "noun",
        "I love my job.",
        "Tôi yêu công việc của mình.",
        ["work"],
        [],
        ["new job"]
      ),
      v(
        "work",
        "/wɜːk/",
        "/wɜːrk/",
        "do a job",
        "làm việc",
        "verb",
        "I work hard.",
        "Tôi làm việc chăm chỉ.",
        ["labor"],
        ["rest"],
        ["hard work"]
      ),
    ],
    B1: [
      v(
        "colleague",
        "/ˈkɒliːɡ/",
        "/ˈkɑːliːɡ/",
        "person you work with",
        "đồng nghiệp",
        "noun",
        "My colleagues are helpful.",
        "Đồng nghiệp tôi hay giúp đỡ.",
        ["coworker"],
        [],
        ["senior colleague"]
      ),
      v(
        "schedule",
        "/ˈʃedjuːl/",
        "/ˈskedʒuːl/",
        "plan of times",
        "lịch trình",
        "noun",
        "Check the schedule.",
        "Kiểm tra lịch trình.",
        ["timetable"],
        [],
        ["busy schedule"]
      ),
      v(
        "deadline",
        "/ˈdedlaɪn/",
        "/ˈdedlaɪn/",
        "time limit",
        "hạn chót",
        "noun",
        "The deadline is tomorrow.",
        "Hạn chót là ngày mai.",
        [],
        [],
        ["meet deadline"]
      ),
      v(
        "report",
        "/rɪˈpɔːt/",
        "/rɪˈpɔːrt/",
        "written document",
        "báo cáo",
        "noun",
        "Write a report.",
        "Viết báo cáo.",
        [],
        [],
        ["monthly report"]
      ),
      v(
        "salary",
        "/ˈsæləri/",
        "/ˈsæləri/",
        "money for work",
        "lương",
        "noun",
        "She gets a good salary.",
        "Cô ấy nhận lương cao.",
        ["wage"],
        [],
        ["high salary"]
      ),
      v(
        "task",
        "/tɑːsk/",
        "/tæsk/",
        "piece of work",
        "nhiệm vụ",
        "noun",
        "Finish the task.",
        "Hoàn thành nhiệm vụ.",
        ["job"],
        [],
        ["daily task"]
      ),
      v(
        "meeting",
        "/ˈmiːtɪŋ/",
        "/ˈmiːtɪŋ/",
        "gathering of people",
        "cuộc họp",
        "noun",
        "We have a meeting.",
        "Chúng tôi có cuộc họp.",
        [],
        [],
        ["staff meeting"]
      ),
      v(
        "assistant",
        "/əˈsɪstənt/",
        "/əˈsɪstənt/",
        "helper",
        "trợ lý",
        "noun",
        "He is my assistant.",
        "Anh ấy là trợ lý của tôi.",
        ["helper"],
        [],
        ["personal assistant"]
      ),
      v(
        "document",
        "/ˈdɒkjumənt/",
        "/ˈdɑːkjumənt/",
        "official paper",
        "tài liệu",
        "noun",
        "Sign the document.",
        "Ký tài liệu.",
        ["paper"],
        [],
        ["legal document"]
      ),
      v(
        "client",
        "/ˈklaɪənt/",
        "/ˈklaɪənt/",
        "customer using service",
        "khách hàng",
        "noun",
        "We have a new client.",
        "Chúng ta có khách hàng mới.",
        ["customer"],
        [],
        ["important client"]
      ),
    ],
    C1: [
      v(
        "bureaucracy",
        "/bjʊəˈrɒkrəsi/",
        "/bjʊˈrɑːkrəsi/",
        "complicated rules",
        "quan liêu",
        "noun",
        "Too much bureaucracy slows us down.",
        "Quá nhiều thủ tục quan liêu làm chậm chúng ta.",
        ["red tape"],
        [],
        ["government bureaucracy"]
      ),
      v(
        "workflow",
        "/ˈwɜːkfləʊ/",
        "/ˈwɜːrkfloʊ/",
        "sequence of processes",
        "quy trình làm việc",
        "noun",
        "Improve the workflow.",
        "Cải thiện quy trình làm việc.",
        [],
        [],
        ["efficient workflow"]
      ),
      v(
        "collaborate",
        "/kəˈlæbəreɪt/",
        "/kəˈlæbəreɪt/",
        "work together",
        "cộng tác",
        "verb",
        "We collaborate on projects.",
        "Chúng tôi cộng tác trong các dự án.",
        ["cooperate"],
        [],
        ["collaborate with"]
      ),
      v(
        "productive",
        "/prəˈdʌktɪv/",
        "/prəˈdʌktɪv/",
        "producing good results",
        "năng suất",
        "adjective",
        "It was a productive day.",
        "Đó là một ngày năng suất.",
        ["efficient"],
        ["unproductive"],
        ["highly productive"]
      ),
      v(
        "workload",
        "/ˈwɜːkləʊd/",
        "/ˈwɜːrkloʊd/",
        "amount of work",
        "khối lượng công việc",
        "noun",
        "The workload is heavy.",
        "Khối lượng công việc rất nặng.",
        [],
        [],
        ["manage workload"]
      ),
      v(
        "delegate",
        "/ˈdelɪɡeɪt/",
        "/ˈdelɪɡeɪt/",
        "give work to others",
        "ủy quyền/giao việc",
        "verb",
        "Learn to delegate tasks.",
        "Học cách giao việc.",
        ["assign"],
        [],
        ["delegate authority"]
      ),
      v(
        "executive",
        "/ɪɡˈzekjətɪv/",
        "/ɪɡˈzekjətɪv/",
        "senior manager",
        "người điều hành",
        "noun",
        "He is a top executive.",
        "Ông ấy là lãnh đạo cấp cao.",
        ["manager"],
        [],
        ["chief executive"]
      ),
      v(
        "cubicle",
        "/ˈkjuːbɪkl/",
        "/ˈkjuːbɪkl/",
        "small workspace",
        "vách ngăn làm việc",
        "noun",
        "I work in a cubicle.",
        "Tôi làm việc trong vách ngăn.",
        [],
        [],
        ["office cubicle"]
      ),
      v(
        "stationery",
        "/ˈsteɪʃənri/",
        "/ˈsteɪʃəneri/",
        "office supplies",
        "văn phòng phẩm",
        "noun",
        "Order more stationery.",
        "Đặt thêm văn phòng phẩm.",
        [],
        [],
        ["stationery cupboard"]
      ),
      v(
        "archive",
        "/ˈɑːkaɪv/",
        "/ˈɑːrkaɪv/",
        "collection of records",
        "lưu trữ",
        "noun",
        "Check the archive.",
        "Kiểm tra kho lưu trữ.",
        ["record"],
        [],
        ["digital archive"]
      ),
    ],
  },
  "Job Hunting": {
    A2: [
      v(
        "resume",
        "/ˈrezjuːmeɪ/",
        "/ˈrezəmeɪ/",
        "document of experience",
        "sơ yếu lý lịch",
        "noun",
        "Send your resume.",
        "Gửi CV của bạn.",
        ["CV"],
        [],
        ["send resume"]
      ),
      v(
        "interview",
        "/ˈɪntəvjuː/",
        "/ˈɪntərvjuː/",
        "meeting for job",
        "phỏng vấn",
        "noun",
        "I have a job interview.",
        "Tôi có buổi phỏng vấn.",
        [],
        [],
        ["job interview"]
      ),
      v(
        "apply",
        "/əˈplaɪ/",
        "/əˈplaɪ/",
        "ask for job",
        "ứng tuyển",
        "verb",
        "Apply for the job.",
        "Ứng tuyển công việc.",
        [],
        [],
        ["apply online"]
      ),
      v(
        "hired",
        "/ˈhaɪəd/",
        "/ˈhaɪərd/",
        "given a job",
        "được thuê",
        "adjective",
        "You are hired!",
        "Bạn đã được thuê!",
        ["employed"],
        ["fired"],
        ["get hired"]
      ),
      v(
        "skill",
        "/skɪl/",
        "/skɪl/",
        "ability to do something",
        "kỹ năng",
        "noun",
        "She has many skills.",
        "Cô ấy có nhiều kỹ năng.",
        ["ability"],
        [],
        ["new skill"]
      ),
      v(
        "experience",
        "/ɪkˈspɪəriəns/",
        "/ɪkˈspɪriəns/",
        "knowledge from doing",
        "kinh nghiệm",
        "noun",
        "Do you have experience?",
        "Bạn có kinh nghiệm không?",
        [],
        [],
        ["work experience"]
      ),
      v(
        "manager",
        "/ˈmænɪdʒər/",
        "/ˈmænɪdʒər/",
        "person who controls",
        "quản lý",
        "noun",
        "Talk to the manager.",
        "Nói chuyện với quản lý.",
        ["boss"],
        [],
        ["project manager"]
      ),
      v(
        "company",
        "/ˈkʌmpəni/",
        "/ˈkʌmpəni/",
        "business organization",
        "công ty",
        "noun",
        "It is a big company.",
        "Đó là công ty lớn.",
        ["firm"],
        [],
        ["tech company"]
      ),
      v(
        "contract",
        "/ˈkɒntrækt/",
        "/ˈkɑːntrækt/",
        "legal agreement",
        "hợp đồng",
        "noun",
        "Sign the contract.",
        "Ký hợp đồng.",
        ["agreement"],
        [],
        ["sign contract"]
      ),
      v(
        "full-time",
        "/ˌfʊl ˈtaɪm/",
        "/ˌfʊl ˈtaɪm/",
        "working all hours",
        "toàn thời gian",
        "adjective",
        "It is a full-time job.",
        "Việc làm toàn thời gian.",
        [],
        ["part-time"],
        ["full-time job"]
      ),
    ],
    B2: [
      v(
        "qualification",
        "/ˌkwɒlɪfɪˈkeɪʃn/",
        "/ˌkwɑːlɪfɪˈkeɪʃn/",
        "exam passed/skill",
        "bằng cấp/trình độ",
        "noun",
        "List your qualifications.",
        "Liệt kê bằng cấp của bạn.",
        ["credential"],
        [],
        ["academic qualification"]
      ),
      v(
        "vacancy",
        "/ˈveɪkənsi/",
        "/ˈveɪkənsi/",
        "available job",
        "vị trí trống",
        "noun",
        "There is a vacancy.",
        "Có một vị trí trống.",
        ["opening"],
        [],
        ["job vacancy"]
      ),
      v(
        "recruit",
        "/rɪˈkruːt/",
        "/rɪˈkruːt/",
        "find new people",
        "tuyển dụng",
        "verb",
        "They are recruiting now.",
        "Họ đang tuyển dụng.",
        ["hire"],
        [],
        ["recruit staff"]
      ),
      v(
        "reference",
        "/ˈrefrəns/",
        "/ˈrefrəns/",
        "letter focusing on you",
        "thư giới thiệu",
        "noun",
        "Provide two references.",
        "Cung cấp 2 người tham khảo.",
        ["recommendation"],
        [],
        ["character reference"]
      ),
      v(
        "candidate",
        "/ˈkændɪdət/",
        "/ˈkændɪdeɪt/",
        "person applying",
        "ứng viên",
        "noun",
        "He is a strong candidate.",
        "Anh ấy là ứng viên mạnh.",
        ["applicant"],
        [],
        ["job candidate"]
      ),
      v(
        "opportunity",
        "/ˌɒpəˈtjuːnəti/",
        "/ˌɑːpərˈtuːnəti/",
        "chance to do specific",
        "cơ hội",
        "noun",
        "This is a great opportunity.",
        "Đây là cơ hội tuyệt vời.",
        ["chance"],
        [],
        ["career opportunity"]
      ),
      v(
        "promotion",
        "/prəˈməʊʃn/",
        "/prəˈmoʊʃn/",
        "better job level",
        "thăng chức",
        "noun",
        "She got a promotion.",
        "Cô ấy được thăng chức.",
        ["advancement"],
        ["demotion"],
        ["get promotion"]
      ),
      v(
        "temporary",
        "/ˈtemprəri/",
        "/ˈtempəreri/",
        "not permanent",
        "tạm thời",
        "adjective",
        "It is a temporary role.",
        "Đây là vai trò tạm thời.",
        ["short-term"],
        ["permanent"],
        ["temporary job"]
      ),
      v(
        "career",
        "/kəˈrɪər/",
        "/kəˈrɪr/",
        "working life",
        "sự nghiệp",
        "noun",
        "Build a career.",
        "Xây dựng sự nghiệp.",
        ["profession"],
        [],
        ["career path"]
      ),
      v(
        "probation",
        "/prəˈbeɪʃn/",
        "/proʊˈbeɪʃn/",
        "trial period",
        "tập sự/thử việc",
        "noun",
        "He is on probation.",
        "Anh ấy đang thử việc.",
        [],
        [],
        ["probation period"]
      ),
    ],
    C2: [
      v(
        "headhunter",
        "/ˈhedhʌntər/",
        "/ˈhedhʌntər/",
        "recruiter of top staff",
        "nhà tuyển dụng cấp cao",
        "noun",
        "A headhunter called me.",
        "Một người săn đầu người gọi tôi.",
        ["recruiter"],
        [],
        ["executive headhunter"]
      ),
      v(
        "remuneration",
        "/rɪˌmjuːnəˈreɪʃn/",
        "/rɪˌmjuːnəˈreɪʃn/",
        "pay and benefits",
        "thù lao",
        "noun",
        "The remuneration is generous.",
        "Thù lao rất hậu hĩnh.",
        ["compensation"],
        [],
        ["annual remuneration"]
      ),
      v(
        "tenure",
        "/ˈtenjər/",
        "/ˈtenjər/",
        "permanent job status",
        "biên chế/nhiệm kỳ",
        "noun",
        "Professors get tenure.",
        "Giáo sư được vào biên chế.",
        [],
        [],
        ["grant tenure"]
      ),
      v(
        "dismissal",
        "/dɪsˈmɪsl/",
        "/dɪsˈmɪsl/",
        "being fired",
        "sự sa thải",
        "noun",
        "Constructive dismissal is illegal.",
        "Sa thải ép buộc là phạm pháp.",
        ["firing"],
        ["hiring"],
        ["unfair dismissal"]
      ),
      v(
        "resignation",
        "/ˌrezɪɡˈneɪʃn/",
        "/ˌrezɪɡˈneɪʃn/",
        "act of quitting",
        "sự từ chức",
        "noun",
        "Hand in resignation.",
        "Nộp đơn từ chức.",
        [],
        [],
        ["letter of resignation"]
      ),
      v(
        "poach",
        "/pəʊtʃ/",
        "/poʊtʃ/",
        "steal staff",
        "câu kéo nhân sự",
        "verb",
        "Competitors poached our staff.",
        "Đối thủ câu kéo nhân viên chúng tôi.",
        ["steal"],
        [],
        ["poach talent"]
      ),
      v(
        "redundancy",
        "/rɪˈdʌndənsi/",
        "/rɪˈdʌndənsi/",
        "losing job due to cuts",
        "sự giảm biên chế",
        "noun",
        "Face redundancy.",
        "Đối mặt với giảm biên chế.",
        ["layoff"],
        [],
        ["voluntary redundancy"]
      ),
      v(
        "sabbatical",
        "/səˈbætɪkl/",
        "/səˈbætɪkl/",
        "break from work",
        "kỳ nghỉ phép dài hạn",
        "noun",
        "Take a sabbatical year.",
        "Nghỉ phép một năm.",
        ["leave"],
        [],
        ["on sabbatical"]
      ),
      v(
        "apprentice",
        "/əˈprentɪs/",
        "/əˈprentɪs/",
        "learner of trade",
        "người học việc",
        "noun",
        "He is an apprentice plumber.",
        "Anh ấy là thợ sửa ống nước học việc.",
        ["trainee"],
        [],
        ["join as apprentice"]
      ),
      v(
        "cover letter",
        "/ˈkʌvər letər/",
        "/ˈkʌvər letər/",
        "letter with resume",
        "thu xin việc",
        "noun",
        "Write a cover letter.",
        "Viết thư xin việc.",
        [],
        [],
        ["send cover letter"]
      ),
    ],
  },
  Meetings: {
    A1: [
      v(
        "meet",
        "/miːt/",
        "/miːt/",
        "come together",
        "gặp gỡ",
        "verb",
        "Let's meet tomorrow.",
        "Gặp nhau ngày mai nhé.",
        [],
        [],
        ["meet friends"]
      ),
      v(
        "talk",
        "/tɔːk/",
        "/tɔːk/",
        "speak",
        "nói chuyện",
        "verb",
        "We need to talk.",
        "Chúng ta cần nói chuyện.",
        ["speak"],
        [],
        ["talk about"]
      ),
      v(
        "listen",
        "/ˈlɪsn/",
        "/ˈlɪsn/",
        "hear with attention",
        "lắng nghe",
        "verb",
        "Please listen.",
        "Làm ơn hãy nghe.",
        ["hear"],
        [],
        ["listen carefully"]
      ),
      v(
        "ask",
        "/ɑːsk/",
        "/æsk/",
        "question",
        "hỏi",
        "verb",
        "Ask a question.",
        "Đặt câu hỏi.",
        ["inquire"],
        [],
        ["ask for"]
      ),
      v(
        "answer",
        "/ˈɑːnsər/",
        "/ˈænsər/",
        "reply",
        "trả lời",
        "verb",
        "Answer me.",
        "Trả lời tôi đi.",
        ["reply"],
        [],
        ["answer question"]
      ),
      v(
        "time",
        "/taɪm/",
        "/taɪm/",
        "when something happens",
        "thời gian",
        "noun",
        "What time is it?",
        "Mấy giờ rồi?",
        [],
        [],
        ["on time"]
      ),
      v(
        "late",
        "/leɪt/",
        "/leɪt/",
        "not on time",
        "muộn",
        "adjective",
        "Don't be late.",
        "Đừng đến muộn.",
        [],
        ["early"],
        ["too late"]
      ),
      v(
        "plan",
        "/plæn/",
        "/plæn/",
        "idea for doing",
        "kế hoạch",
        "noun",
        "It is a good plan.",
        "Đó là kế hoạch tốt.",
        [],
        [],
        ["make plan"]
      ),
      v(
        "idea",
        "/aɪˈdɪə/",
        "/aɪˈdiːə/",
        "thought",
        "ý tưởng",
        "noun",
        "I have an idea.",
        "Tôi có ý tưởng.",
        ["thought"],
        [],
        ["good idea"]
      ),
      v(
        "team",
        "/tiːm/",
        "/tiːm/",
        "group of people",
        "nhóm/đội",
        "noun",
        "We are a team.",
        "Chúng ta là một đội.",
        ["group"],
        [],
        ["team member"]
      ),
    ],
    B1: [
      v(
        "agenda",
        "/əˈdʒendə/",
        "/əˈdʒendə/",
        "list of topics",
        "chương trình nghị sự",
        "noun",
        "What is on the agenda?",
        "Trong chương trình có gì?",
        ["schedule"],
        [],
        ["meeting agenda"]
      ),
      v(
        "present",
        "/prɪˈzent/",
        "/prɪˈzent/",
        "show and explain",
        "trình bày",
        "verb",
        "Present your work.",
        "Trình bày công việc của bạn.",
        ["show"],
        [],
        ["present ideas"]
      ),
      v(
        "discuss",
        "/dɪˈskʌs/",
        "/dɪˈskʌs/",
        "talk about",
        "thảo luận",
        "verb",
        "Let's discuss this.",
        "Hãy thảo luận việc này.",
        ["talk"],
        [],
        ["discuss problem"]
      ),
      v(
        "minutes",
        "/ˈmɪnɪts/",
        "/ˈmɪnɪts/",
        "written record",
        "biên bản cuộc họp",
        "noun",
        "Take the minutes.",
        "Ghi biên bản.",
        ["notes"],
        [],
        ["meeting minutes"]
      ),
      v(
        "chair",
        "/tʃeər/",
        "/tʃer/",
        "person leading",
        "chủ trì",
        "verb",
        "She will chair the meeting.",
        "Cô ấy sẽ chủ trì cuộc họp.",
        ["lead"],
        [],
        ["chair meeting"]
      ),
      v(
        "attend",
        "/əˈtend/",
        "/əˈtend/",
        "go to",
        "tham dự",
        "verb",
        "Attend the conference.",
        "Tham dự hội nghị.",
        ["go to"],
        [],
        ["attend meeting"]
      ),
      v(
        "apology",
        "/əˈpɒlədʒi/",
        "/əˈpɑːlədʒi/",
        "saying sorry for absence",
        "lời cáo lỗi",
        "noun",
        "Send apologies.",
        "Gửi lời cáo lỗi vắng mặt.",
        [],
        [],
        ["accept apology"]
      ),
      v(
        "propose",
        "/prəˈpəʊz/",
        "/prəˈpoʊz/",
        "suggest",
        "đề xuất",
        "verb",
        "I propose a change.",
        "Tôi đề xuất thay đổi.",
        ["suggest"],
        [],
        ["propose plan"]
      ),
      v(
        "agree",
        "/əˈɡriː/",
        "/əˈɡriː/",
        "say yes",
        "đồng ý",
        "verb",
        "We agree with you.",
        "Chúng tôi đồng ý với bạn.",
        ["concur"],
        ["disagree"],
        ["fully agree"]
      ),
      v(
        "vote",
        "/vəʊt/",
        "/voʊt/",
        "choose",
        "bỏ phiếu",
        "verb",
        "Let's vote.",
        "Hãy bỏ phiếu.",
        ["elect"],
        [],
        ["cast vote"]
      ),
    ],
    C2: [
      v(
        "consensus",
        "/kənˈsensəs/",
        "/kənˈsensəs/",
        "general agreement",
        "sự đồng thuận",
        "noun",
        "Reach a consensus.",
        "Đạt được sự đồng thuận.",
        ["agreement"],
        ["disagreement"],
        ["general consensus"]
      ),
      v(
        "unanimous",
        "/juˈnænɪməs/",
        "/juˈnænɪməs/",
        "all agreeing",
        "nhất trí",
        "adjective",
        "The decision was unanimous.",
        "Quyết định là nhất trí.",
        ["united"],
        [],
        ["unanimous vote"]
      ),
      v(
        "quorum",
        "/ˈkwɔːrəm/",
        "/ˈkwɔːrəm/",
        "min number of people",
        "số lượng ối thiểu",
        "noun",
        "We do not have a quorum.",
        "Chúng ta không đủ số lượng tối thiểu.",
        [],
        [],
        ["establish quorum"]
      ),
      v(
        "motion",
        "/ˈməʊʃn/",
        "/ˈmoʊʃn/",
        "proposal",
        "kiến nghị",
        "noun",
        "Second the motion.",
        "Tán thành kiến nghị.",
        ["proposal"],
        [],
        ["pass motion"]
      ),
      v(
        "adjourn",
        "/əˈdʒɜːn/",
        "/əˈdʒɜːrn/",
        "stop meeting",
        "hoãn/kết thúc",
        "verb",
        "The meeting adjourned.",
        "Cuộc họp kết thúc.",
        ["close"],
        [],
        ["adjourn meeting"]
      ),
      v(
        "brainstorm",
        "/ˈbreɪnstɔːm/",
        "/ˈbreɪnstɔːrm/",
        "think of ideas",
        "động não",
        "verb",
        "Brainstorm solutions.",
        "Động não tìm giải pháp.",
        [],
        [],
        ["brainstorm session"]
      ),
      v(
        "negotiate",
        "/nɪˈɡəʊʃieɪt/",
        "/nɪˈɡoʊʃieɪt/",
        "bargain for agreement",
        "đàm phán",
        "verb",
        "Negotiate a deal.",
        "Đàm phán thỏa thuận.",
        ["bargain"],
        [],
        ["negotiate terms"]
      ),
      v(
        "standpoint",
        "/ˈstændpɔɪnt/",
        "/ˈstændpɔɪnt/",
        "point of view",
        "quan điểm",
        "noun",
        "From my standpoint.",
        "Từ quan điểm của tôi.",
        ["perspective"],
        [],
        ["personal standpoint"]
      ),
      v(
        "deadlock",
        "/ˈdedlɒk/",
        "/ˈdedlɑːk/",
        "no agreement possible",
        "sự bế tắc",
        "noun",
        "Negotiations reached a deadlock.",
        "Đàm phán đi vào bế tắc.",
        ["stalemate"],
        [],
        ["break deadlock"]
      ),
      v(
        "AGM",
        "/ˌeɪ dʒiː ˈem/",
        "/ˌeɪ dʒiː ˈem/",
        "Annual General Meeting",
        "đại hội cổ đông thường niên",
        "noun",
        "Attend the AGM.",
        "Tham dự đại hội cổ đông.",
        [],
        [],
        ["company AGM"]
      ),
    ],
  },
  "Business Terms": {
    B1: [
      v(
        "profit",
        "/ˈprɒfɪt/",
        "/ˈprɑːfɪt/",
        "money made",
        "lợi nhuận",
        "noun",
        "Make a profit.",
        "Tạo ra lợi nhuận.",
        ["gain"],
        ["loss"],
        ["net profit"]
      ),
      v(
        "loss",
        "/lɒs/",
        "/lɔːs/",
        "money lost",
        "thua lỗ",
        "noun",
        "Avoid a loss.",
        "Tránh thua lỗ.",
        [],
        ["profit"],
        ["big loss"]
      ),
      v(
        "market",
        "/ˈmɑːkɪt/",
        "/ˈmɑːrkɪt/",
        "place for trade",
        "thị trường",
        "noun",
        "The global market.",
        "Thị trường toàn cầu.",
        [],
        [],
        ["stock market"]
      ),
      v(
        "product",
        "/ˈprɒdʌkt/",
        "/ˈprɑːdʌkt/",
        "thing made to sell",
        "sản phẩm",
        "noun",
        "Launch a new product.",
        "Ra mắt sản phẩm mới.",
        ["goods"],
        [],
        ["quality product"]
      ),
      v(
        "service",
        "/ˈsɜːvɪs/",
        "/ˈsɜːrvɪs/",
        "help provided",
        "dịch vụ",
        "noun",
        "Customer service.",
        "Dịch vụ khách hàng.",
        [],
        [],
        ["good service"]
      ),
      v(
        "invest",
        "/ɪnˈvest/",
        "/ɪnˈvest/",
        "put money in",
        "đầu tư",
        "verb",
        "Invest in shares.",
        "Đầu tư vào cổ phiếu.",
        [],
        [],
        ["invest money"]
      ),
      v(
        "budget",
        "/ˈbʌdʒɪt/",
        "/ˈbʌdʒɪt/",
        "plan for money",
        "ngân sách",
        "noun",
        "Within the budget.",
        "Trong ngân sách.",
        [],
        [],
        ["tight budget"]
      ),
      v(
        "tax",
        "/tæks/",
        "/tæks/",
        "money to government",
        "thuế",
        "noun",
        "Pay tax.",
        "Nộp thuế.",
        [],
        [],
        ["income tax"]
      ),
      v(
        "economy",
        "/ɪˈkɒnəmi/",
        "/ɪˈkɑːnəmi/",
        "system of money",
        "nền kinh tế",
        "noun",
        "The economy is growing.",
        "Kinh tế đang tăng trưởng.",
        [],
        [],
        ["global economy"]
      ),
      v(
        "growth",
        "/ɡrəʊθ/",
        "/ɡroʊθ/",
        "getting bigger",
        "sự tăng trưởng",
        "noun",
        "Business growth.",
        "Tăng trưởng kinh doanh.",
        ["expansion"],
        [],
        ["economic growth"]
      ),
    ],
    B2: [
      v(
        "shareholder",
        "/ˈʃeəhəʊldər/",
        "/ˈʃerhoʊldər/",
        "person owning shares",
        "cổ đông",
        "noun",
        "Shareholders want profit.",
        "Cổ đông muốn lợi nhuận.",
        ["stockholder"],
        [],
        ["major shareholder"]
      ),
      v(
        "merger",
        "/ˈmɜːdʒər/",
        "/ˈmɜːrdʒər/",
        "joining of companies",
        "sự sáp nhập",
        "noun",
        "A merger between banks.",
        "Sáp nhập giữa các ngân hàng.",
        ["union"],
        [],
        ["merger and acquisition"]
      ),
      v(
        "competitor",
        "/kəmˈpetɪtər/",
        "/kəmˈpetɪtər/",
        "business rival",
        "đối thủ cạnh tranh",
        "noun",
        "Beat the competitor.",
        "Đánh bại đối thủ.",
        ["rival"],
        [],
        ["main competitor"]
      ),
      v(
        "expansion",
        "/ɪkˈspænʃn/",
        "/ɪkˈspænʃn/",
        "getting larger",
        "sự mở rộng",
        "noun",
        "Expansion into new markets.",
        "Mở rộng sang thị trường mới.",
        ["growth"],
        [],
        ["rapid expansion"]
      ),
      v(
        "turnover",
        "/ˈtɜːnəʊvər/",
        "/ˈtɜːrnoʊvər/",
        "total sales",
        "doanh thu",
        "noun",
        "Annual turnover.",
        "Doanh thu hàng năm.",
        ["revenue"],
        [],
        ["high turnover"]
      ),
      v(
        "stake",
        "/steɪk/",
        "/steɪk/",
        "share in business",
        "cổ phần",
        "noun",
        "Hold a stake.",
        "Nắm giữ cổ phần.",
        ["share"],
        [],
        ["majority stake"]
      ),
      v(
        "bankrupt",
        "/ˈbæŋkrʌpt/",
        "/ˈbæŋkrʌpt/",
        "no money left",
        "phá sản",
        "adjective",
        "Go bankrupt.",
        "Bị phá sản.",
        ["insolvent"],
        [],
        ["declare bankrupt"]
      ),
      v(
        "currency",
        "/ˈkʌrənsi/",
        "/ˈkɜːrənsi/",
        "type of money",
        "tiền tệ",
        "noun",
        "Foreign currency.",
        "Ngoại tệ.",
        ["money"],
        [],
        ["strong currency"]
      ),
      v(
        "asset",
        "/ˈæset/",
        "/ˈæset/",
        "something valuable",
        "tài sản",
        "noun",
        "Protect your assets.",
        "Bảo vệ tài sản.",
        ["property"],
        ["liability"],
        ["liquid asset"]
      ),
      v(
        "liability",
        "/ˌlaɪəˈbɪləti/",
        "/ˌlaɪəˈbɪləti/",
        "debt/responsibility",
        "nghĩa vụ/khoản nợ",
        "noun",
        "Limit liability.",
        "Giới hạn trách nhiệm pháp lý.",
        ["debt"],
        ["asset"],
        ["legal liability"]
      ),
    ],
    C1: [
      v(
        "monopoly",
        "/məˈnɒpəli/",
        "/məˈnɑːpəli/",
        "one seller control",
        "độc quyền",
        "noun",
        "Break the monopoly.",
        "Phá vỡ thế độc quyền.",
        [],
        [],
        ["state monopoly"]
      ),
      v(
        "subsidiary",
        "/səbˈsɪdiəri/",
        "/səbˈsɪdieri/",
        "company owned by another",
        "công ty con",
        "noun",
        "A subsidiary of a large firm.",
        "Công ty con của tập đoàn lớn.",
        ["branch"],
        ["parent company"],
        ["local subsidiary"]
      ),
      v(
        "entrepreneur",
        "/ˌɒntrəprəˈnɜːr/",
        "/ˌɑːntrəprəˈnɜːr/",
        "business creator",
        "doanh nhân",
        "noun",
        "Successful entrepreneur.",
        "Doanh nhân thành đạt.",
        ["businessperson"],
        [],
        ["tech entrepreneur"]
      ),
      v(
        "dividend",
        "/ˈdɪvɪdend/",
        "/ˈdɪvɪdend/",
        "profit share",
        "cổ tức",
        "noun",
        "Pay dividends.",
        "Trả cổ tức.",
        [],
        [],
        ["annual dividend"]
      ),
      v(
        "outsourcing",
        "/ˈaʊtsɔːsɪŋ/",
        "/ˈaʊtsɔːrsɪŋ/",
        "using outside workers",
        "thuê ngoài",
        "noun",
        "Save money by outsourcing.",
        "Tiết kiệm tiền bằng cách thuê ngoài.",
        ["contracting"],
        [],
        ["offshore outsourcing"]
      ),
      v(
        "franchise",
        "/ˈfræntʃaɪz/",
        "/ˈfræntʃaɪz/",
        "business license",
        "nhượng quyền",
        "noun",
        "Buy a franchise.",
        "Mua nhượng quyền.",
        [],
        [],
        ["fast food franchise"]
      ),
      v(
        "audit",
        "/ˈɔːdɪt/",
        "/ˈɔːdɪt/",
        "check of accounts",
        "kiểm toán",
        "noun",
        "Internal audit.",
        "Kiểm toán nội bộ.",
        ["inspection"],
        [],
        ["financial audit"]
      ),
      v(
        "deficit",
        "/ˈdefɪsɪt/",
        "/ˈdefɪsɪt/",
        "loss of money",
        "thâm hụt",
        "noun",
        "Budget deficit.",
        "Thâm hụt ngân sách.",
        ["shortfall"],
        ["surplus"],
        ["trade deficit"]
      ),
      v(
        "surplus",
        "/ˈsɜːpləs/",
        "/ˈsɜːrpləs/",
        "extra amount",
        "thặng dư",
        "noun",
        "Trade surplus.",
        "Thặng dư thương mại.",
        ["excess"],
        ["deficit"],
        ["budget surplus"]
      ),
      v(
        "inflation",
        "/ɪnˈfleɪʃn/",
        "/ɪnˈfleɪʃn/",
        "rising prices",
        "lạm phát",
        "noun",
        "High inflation.",
        "Lạm phát cao.",
        [],
        ["deflation"],
        ["rate of inflation"]
      ),
    ],
  },
};

// Seed function
async function seedVocab() {
  console.log("🌱 Seeding Vocabulary Data - Work & Career...");

  // Get or create topic group
  const topicGroup = await prisma.topicGroup.upsert({
    where: { name_hubType: { name: "Work & Career", hubType: "vocab" } },
    update: {},
    create: {
      name: "Work & Career",
      order: 2,
      hubType: "vocab",
      subcategories: [
        "Office Basics",
        "Job Hunting",
        "Meetings",
        "Business Terms",
      ],
    },
  });

  // Helper to slugify
  const slugify = (text: string) =>
    text.toLowerCase().replace(/&/g, "and").replace(/\s+/g, "-");

  // Iterate over subcategories
  for (const [subcat, levelsData] of Object.entries(workCareerVocab)) {
    console.log(`Processing Subcategory: ${subcat}`);

    // Iterate over levels
    for (const [level, vocabItems] of Object.entries(levelsData)) {
      const currentLevel = level as Level;
      const items = vocabItems as ReturnType<typeof v>[];

      if (!items || items.length === 0) continue;

      const topicId = `work-career-${slugify(
        subcat
      )}-${currentLevel.toLowerCase()}`;

      const topic = await prisma.topic.upsert({
        where: { id: topicId },
        update: { wordCount: items.length },
        create: {
          id: topicId,
          title: `${subcat} - ${currentLevel}`,
          subtitle: `Vocabulary about ${subcat.toLowerCase()}`,
          description: `Learn essential vocabulary about ${subcat.toLowerCase()} at ${currentLevel} level.`,
          level: currentLevel,
          wordCount: items.length,
          estimatedTime: Math.ceil(items.length * 2),
          category: "Work & Career",
          subcategory: subcat,
          order: LEVELS.indexOf(currentLevel),
          topicGroupId: topicGroup.id,
        },
      });

      // Seed vocab items
      for (const vocab of items) {
        const vocabId = `${topic.id}-${vocab.word
          .toLowerCase()
          .replace(/\s+/g, "-")}`;
        await prisma.vocabItem.upsert({
          where: { id: vocabId },
          update: vocab,
          create: {
            id: vocabId,
            topicId: topic.id,
            ...vocab,
          },
        });
      }
      console.log(
        `✅ Created: ${subcat} - ${currentLevel} (${items.length} words)`
      );
    }
  }

  console.log("✅ Work & Career seeded successfully!");
}

async function main() {
  try {
    await seedVocab();
  } catch (error) {
    console.error("❌ Error:", error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

main();
